apiVersion: v1
kind: Service
metadata:
  name: kubia-svc
  namespace: jy-test
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: kubia
  sessionAffinity: ClientIP
