apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
  namespace: jy-test
spec:
  replicas: 2
  selector:
    app: kubia
  template:
    metadata:
      name: kubia-v2
      namespace: jy-test
      labels:
        env: test
        lang: java
        app: kubia
    spec:
      containers:
        - name: kubia
          image: registry.cn-hangzhou.aliyuncs.com/jy-test/kubia
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /
