apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    spec:
      containers:
        - name: demo-job
          image: ubuntu:18.10
          command: ["date"]
      restartPolicy: OnFailure
  completions: 3
  parallelism: 2
  backoffLimit: 3
  activeDeadlineSeconds: 86400
