= Solutions of Algorithm 4th edition
:author: jy
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 3
:toc-title: 目录
:tabsize: 4
:docinfo: shared
:codepath: ../algs/src/test/java/me/jy/algs4

.Resource
* https://book.douban.com/subject/19952400[window="_blank"]

== 基础

=== 基础编程模型

==== 给出以下表达式的值

* stem:[(0+15)/2=7]
* stem:[2.0e-6xx100000000.1 = 200.0000002]
* stem:[true&&false||true&&true=true]

==== 给出以下表达式的类型和值

* stem:[(1+2.236)/2=1.618] `double`
* stem:[1+2+3+4.0=10.0] `double`
* stem:[4.1>=4=true] `boolean`
* stem:[1+2+"3"=33] `string`

==== 判断三个整数是否相等

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.3]
----

==== 下列语句各有什么问题

* `if (a > b) then c = 0;` 没有 `then` 这个关键字.
* `if a > b {c = 0; }` a>b没有括号.
* `if (a > b) c = 0;` 对.
* `if (a > b) c = 0 else b = 0;` c=0缺少分号.

==== 判断x, y都不在0和1之间

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.5]
----

==== 下面这段程序会打印出什么

 0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610

==== 分别打印下列代码的值

* 5.0, 3.0
* 499500
* 10000

==== 打印结果

* b
* 197
* e

==== 将正整数N表示成二进制数

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.9]
----

==== 下列代码有什么问题

 数组没有初始化

==== 打印二维数组

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.11]
----

==== 打印结果

 0 1 2 3 4 5 6 7 8 9

==== M行N列数组的转置

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.13]
----

==== 返回不大于 stem:[log_2N]的最大整数

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.14]
----

==== histogram方法

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.15]
----

==== 返回值

 311361142246

==== 找出下列递归函数的问题

 临界条件位置不对, 导致爆栈.

==== 计算返回值

* mystery(2, 25) = 50
* mystery(3, 11) = 33
* mystery(a, b) = a * b

==== 斐波拉契数列优化

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.19]
----

==== 计算 stem:[ln(N!)]的值

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.20]
----

==== 打印商

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.21]
----

==== 跟踪二分查找递归方法的深度

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.22]
----

==== 二分查找打印是否在数组中

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.23]
----

==== 跟踪二分查找递归方法的深度

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.24]
----

==== 证明欧几里得算法

 TODO

==== 证明以下代码能让abc按照升序排列

 ab,bc,ac按照升序排列, 那么abc也是按照升序排列

==== 二项分布

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.27]
----

==== 删除重复元素

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.28]
----

==== 返回数组中小于指定键的元素数量

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.29]
----

==== 生成互质数boolean数组

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.30]
----

==== 随机连接

 // TODO

==== 直方图

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.32]
----

==== 矩阵库

[source,java]
----
include::{codepath}/ch1/Matrix.java[]
----

==== 过滤

* 打印出最大的数 `和N无关`
* 打印出所有数的中位数 `保存所有值`
* 打印出第k小的数 `和N无关`
* 打印出所有数的平方和 `和N无关`
* 打印出N个数的平均值 `和N无关`
* 打印出大于平均值的数的百分比 `保存所有值`
* 将N个数按照升序打印 `保存所有值`
* 将N个数按照随机顺序打印 `和N无关`

==== 模拟掷骰子

 // TODO

==== 乱序检查

[source,java]
----
include::{codepath}/ch1/ShuffleTest.java[tag=ex1.1.36]
----

==== 糟糕的打乱

[source,java]
----
include::{codepath}/ch1/ShuffleTest.java[tag=ex1.1.37]
----

==== 二分查找与暴力查找

[source,java]
----
include::{codepath}/ch1/Exercise1_1.java[tag=ex1.1.38]
----

==== 随机匹配

[source,java]
----
include::{codepath}/ch1/RandomMatch.java[]
----

=== 数据抽象

==== 计算两点间的最近距离

[source,java]
----
include::{codepath}/ch1/Point2DScratches.java[]
----

==== 打印所有相交的间隔对

[source,java]
----
include::{codepath}/ch1/Interval1DScratches.java[]
----

==== 生成随机2D间隔对

[source,java]
----
include::{codepath}/ch1/Interval2DScratches.java[]
----

==== 以下代码打印内容

 world
 hello

==== 以下代码打印内容

 Hello World

==== 判断字符串是否互为回环变位

[source,java]
----
include::{codepath}/ch1/CircularShiftPredicate.java[]
----

==== 以下递归函数的返回值是什么

 参数字符串逆序

==== 下列代码的作用是什么

 交换数组a和b

==== 修改二分查找, 统计查找次数

[source,java]
----
include::{codepath}/ch1/Exercise1_2.java[tag=ex1.2.9]
----

==== 可视化计数器

[source,java]
----
include::{codepath}/ch1/VisualCounter.java[]
----

==== 日期校验

[source,java]
----
include::{codepath}/ch1/SmartDate.java[]
----

==== 获取星期

 见 1.2.11

==== 实现Transaction类型

[source,java]
----
include::{codepath}/ch1/Transaction.java[]
----

==== 实现Transaction类型的equals方法

 见 1.2.13

==== 实现readInts方法

[source,java]
----
include::{codepath}/ch1/Exercise1_2.java[tag=ex1.2.15]
----

==== 有理数

[source,java]
----
include::{codepath}/ch1/Rational.java[]
----

==== 有理数的健壮性

 见 1.2.16

==== 累加器的方差

[source,java]
----
include::{codepath}/ch1/Accumlator.java[]
----

==== 字符串解析

 见 1.2.13


=== 背包队列和栈

=== 算法分析

=== union-find算法
