= ComputerScience
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 3
:toc-title: 目录
:tabsize: 4
:docinfo: shared

.Resources
* https://book.douban.com/subject/26912767[window="_blank"]
* https://book.douban.com/subject/27004846[window="_blank"]
* https://book.douban.com/subject/26745780[window="_blank"]
* https://book.douban.com/subject/19952400[window="_blank"]

== CS journey

=== 信息等于位+上下文

系统中所有的信息, 包括磁盘文件和内存中的程序/用户数据以及网络上的数据, 都是比特组成的. 区分不同数据对象的唯一方法就是我们读到这些数据对象时的 *上下文*.
比如, 在不同的上下文中, 一个同样的字节序列可能表示一个整数/浮点数/字符串或者机器指令.

=== 程序被其他程序翻译成不同的格式

编译: 高级程序语言必须被其他程序转化为一系列的低级机器语言指令, 然后这些指令按照一种可执行目标程序的格式(可执行文件)打包, 并以二进制文件的形式保存起来.

.程序编译流程
plantuml::charts/CompilerSystem.puml[format=svg, height=300]

=== 硬件组成

* 总线: 携带信息字节并负责在各个组件间传递.
* I/O设备: 每个I/O设备通过一个设备控制器(主板上的芯片组)或适配器(插在主板插槽上的卡)与I/O总线相连,
* 主存: 处理器执行程序时, 用来存放程序和程序处理的数据.
* 处理器: 解释存储在主存中的指令的引擎. 处理器的核心是程序计数器(PC), PC指向内存中一条指令的地址, 然后处理器从内存中读取指令数据, 解释并执行, 最后更新PC, 使其指向下一条要执行的指令.

=== 存储器层次结构

TIP: 较大的存储设备要比较小的存储设备运行的慢, 快速设备的造价远高于同类的低俗设备.

高速缓存存储器: 作为一个暂存区域, 存放处理器近期可能会需要的信息.

plantuml::charts/StorageDeviceLevel.puml[format=svg, scale=0.5]

=== 操作系统

==== 操作系统基本职责

* 防止硬件被应用程序滥用.
* 向应用程序提供简单一致的机制来控制硬件设备.

==== 操作系统管理

* 进程
* 线程
* 虚拟内存
* 文件

==== 操作系统抽象

plantuml::charts/CSAbstract.puml[format=svg]

=== Amdahl定律

* 系统执行某应用程序所需要的时间为stem:[T_(old)]
* 系统某部分执行时间占比stem:[alpha]
* 该部分性能提升比例stem:[k]

.新的总执行时间
stem:[T_(n\ew)=(1-alpha)T_(old)+alphaT_(old)/k=T_(old)*((1-alpha)+alpha/k)]
.加速比
stem:[S=T_(old)/ T_(n\ew)=1/((1-alpha)+alpha/k]

