= Design Pattern
:icons: font
:sectanchors:
:source-highlighter: rouge
:page-layout: docs
:toc: left
:toc-title: 索引

== 1. 定义

> 对在特定场景下解决设计问题的类或对象的描述.

.模式4个要素
* 名称
* 使用场景
* 模式的组成和设计
* 效果(优缺点)

== 2. 类别

|===
| | | 创建型 | 结构型 | 行为型

| 范围
| 类
| Factory Method
| Adapter(类)
a|
* Interpreter
* Template Method

|
| 对象
a|
* Abstract Factory
* Builder
* Prototype
* Singleton
a|
* Adapter(对象)
* Bridge
* Composite
* Decorator
* Facade
* Flyweight
* Proxy
a|
* Chain of Responsibility
* Command
* Iterator
* Mediator
* Memento
* Observer
* State
* Strategy
* Visitor

|===

== 3. 作用

* 创建型:
** 类: 将对象的部分创建工作延迟到子类
** 对象: 将对象的部分创建工作延迟到另一个对象中
* 结构型:
** 类: 使用继承机制来组合类
** 对象: 描述了对象的组装方法
* 行为型:
** 类: 使用继承描述算法和控制流
** 对象: 描述一组对象协作来完成单个对象无法完成的任务

== 4. 面向对象设计原则

* Single Responsibility Principle: 单一职责原则

 一个类只负责一个功能领域的相应职责.如常用的代码分层: xxRepository负责db/xxService负责逻辑处理

* Open-Closed Principle: 开闭原则

 一个实体类应该尽量在不修改原有代码的基础上扩展.

.OCP(新增Chart不会修改AbstractChartDisplay类的代码)
[plantuml, ocp, svg]
....
interface Chart{
+ void display()
}
class AbstractChartDisplay{
- chart: Chart
+ void setChart(Chart chart)
}
class FooChart{
}
class BarChart{
}

Chart <|.. FooChart
Chart <|.. BarChart
Chart <|.. AbstractChartDisplay
....

* Liskov Substitution Principle: 里氏替换原则

 在程序定义时尽量使用父类类型, 在运行时再去确定子类类型.
 在类设计时, 尽量把子类的方法抽到父类里面.

* Dependency Inversion Principle: 依赖倒转原则

 针对接口编程, 而不是实现类.

* Interface Segregation Principle: 接口隔离原则

 使用多个专门的接口, 而不是单一的接口.

* Composite Reuse Principle: 合成复用原则

 尽量使用对象组合, 而不是继承来达到复用的目的.
 Has-a 使用组合, Is-a 使用继承

* LeastKnowledge Principle: 最小知识原则

 尽量减少对象之间的交互.


== 5. 创建型模式

=== 5.1 Simple Factory模式(静态工厂)

 定义一个工厂类, 根据不同的参数返回不同的类型. 被创建的对象类型通常具有共同的父类.

==== 5.1.1 使用场景
 客户端知道创建对象需要的参数, 不关系对象的创建过程.

==== 5.1.2 优点
* 将对象的创建和对象的使用分离开, 客户端无需知道具体的创建逻辑, 只需知道对象创建需要的参数.

==== 5.1.3 缺点
* 工厂类职责过重, 如果工厂类出现问题, 就会影响整个系统.
* 系统扩展困难, 一旦添加新的产品就要修改工厂逻辑, 违反了开闭原则.

=== 5.2 Factory Method模式

 定义一个创建对象的接口, 让子类决定将哪个类实例化.

==== 5.2.1 使用场景

 客户端不知道它需要的对象的类型

==== 5.2.2 组成

.工厂方法模式UML
[plantuml, factoy-method, svg]
....
interface Product{
}
class ConcreteProduct{
}
interface ProductFactory{
+ Product create()
}
class ConcreteProductFactory{
}
Product <|.. ConcreteProduct
ProductFactory <|.. ConcreteProductFactory
ConcreteProduct <- ConcreteProductFactory
....

==== 5.2.3 优点

* 客户端只需要关心创建产品需要的工厂, 无需关心创建细节

==== 5.2.3 缺点

* 系统文件个数增加

=== 5.3 Abstract Factory模式

 提供一个创建一系列相关对象的接口

==== 5.3.1 使用场景

 生产的多个对象可以规约为多种类型

==== 5.3.2 组成

.抽象工厂模式UML
[plantuml, abstract-factoy, svg]
....
interface ProductA{
}
interface ProductB{
}
class ConcreteProductA{
}
class ConcreteProductB{
}
interface ProductFactory{
+ ProductA createA()
+ ProductB createB()
}
class ConcreteProductFactory1{
}
class ConcreteProductFactory2{
}
ProductA <|.. ConcreteProductA
ProductB <|.. ConcreteProductB
ProductFactory <|.. ConcreteProductFactory1
ProductFactory <|.. ConcreteProductFactory2

ConcreteProductA <- ConcreteProductFactory1
ConcreteProductB <- ConcreteProductFactory1
ConcreteProductA <- ConcreteProductFactory2
ConcreteProductB <- ConcreteProductFactory2
....

==== 5.3.3 优点

* 增加一个产品族的时候只需要增加一个工厂类就行了.

==== 5.3.4 缺点

* 增加一个产品需要修改所有的工厂类.

=== 5.4 Singleton模式

 内部提供一个静态的工厂方法, 获取单个实例

==== 5.4.1 使用场景

 系统中不需要多个实例

==== 5.4.2 组成

.单例模式UML
[plantuml, singleton, svg]
....
class Singleton {
- Singleton INSTANCE = new Singleton()
+ Singleton getInstance()
}
....

==== 5.4.3 优点
* 节约系统资源
* 限制了对实例的访问

==== 5.4.4 缺点
* 扩展困难

=== 5.5 原型模式

 使用原型实例指定创建对象的种类, 并且通过拷贝这些原型创建新的对象.

==== 5.5.1 使用场景

 创建大量内容相同的对象.

==== 5.5.2 组成

.单例模式UML
[plantuml, prototype, svg]
....
class Prototype{
+ Prototype clone()
}
....

==== 5.5.3 优点

* 简化对象的创建过程, 提高新对象的创建效率

==== 5.5.4 缺点

* 为了deep clone, 对象的每一个属性都必须实现deep clone.

=== 5.5 Builder模式

 提供Builder类组装对象

==== 5.5.1 使用场景

 组装的类属性很多, 创建过程复杂, 可以引入builder简化客户端调用.

==== 5.5.2 组成

.单例模式UML
[plantuml, builder, svg]
....
class Product{
}
class Builder{
- Product product
+ Builder a()
+ Builder b()
+ Builder c()
+ Product build()
}
....

==== 5.5.3 优点

* 隔离复杂对象的创建和使用, 并使得相同的创建过程可以创建不同的对象.

== 6. 结构型模式

=== 6.1 Adapter模式
