= Discrete Mathematics
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 3
:toc-title: 目录
:tabsize: 4
:docinfo: shared

.Resources
* https://book.douban.com/subject/27004846[window="_blank"]

== 逻辑和证明

=== 命题逻辑

> 命题是一个陈述事实的语句, 它或真或假, 但不能既为真又为假. 如果一个命题是真命题, 用T表示, 假命题用F表示.

> 令 stem:[p] 为一命题, 则 stem:[p] 的否定记作 stem:[notp].

> 令 stem:[p] 和 stem:[q] 为命题, stem:[p]、stem:[q] 的合取记作 stem:[p^^q]. 当p和q都是真命题时, stem:[p^^q] 为真, 否则为假.

> 令 stem:[p] 和 stem:[q] 为命题, stem:[p]、stem:[q] 的析取记作 stem:[pvvq]. 当p和q都是假命题时, stem:[pvvq] 为假, 否则为真.

> 令 stem:[p] 和 stem:[q] 为命题, stem:[p]、stem:[q] 的异或记作 stem:[po+q]. 当p和q中恰好只有1个真命题时为真, 否则为假.

=== 条件语句

> 令 stem:[p] 和 stem:[q] 为命题, 条件语句 stem:[p->q] 代表命题 "如果p,则q". 当stem:[p]为真且stem:[q]为假时, 条件语句 stem:[p->q] 为假, 否则为真.

* stem:[q->p] 称为 stem:[p->q] 的逆命题.
* stem:[notp->notq] 称为 stem:[p->q]的反命题.
* stem:[notq->notp] 称为 stem:[p->q]的逆否命题.

 逆否命题和原命题有相同的真值.
 逆命题和反命题有相同的真值.

> 令p和q为命题, 双条件语句 stem:[pharrq] 代表命题 "p当且仅当q". 当p和q真值相同时, 双条件语句为真, 否则为假.

=== 复合命题的真值表

[cols="6*^"]
|===
| p | q | stem:[notq] | stem:[pvvnotq] | stem:[p^^q] | stem:[(pvvnotq)->(p^^q)]

| T
| T
| F
| T
| T
| T

| T
| F
| T
| T
| F
| F

| F
| T
| F
| F
| F
| T

| F
| F
| T
| T
| F
| F

|===

=== 命题等价式

* 永真式: 命题永远为真.
* 矛盾式: 命题永远为假.
* 可能式: 命题可能为真, 可能为假.

> 如果 stem:[pharrq] 是永真式, 那么 stem:[p和q] 是逻辑等价的, 记为 stem:[p-=q].

.德·摩根律
* stem:[not(p^^q)-=notpvvnotq] `一个析取式的否定是由各个命题的否定合取而成的`
* stem:[not(pvvq)-=notp^^notq] `一个合取式的否定是由各个命题的否定析取而成的`

.恒等律
* stem:[p^^T-=p]
* stem:[pvvF-=p]

.支配律
* stem:[pvvT-=T]
* stem:[p^^F-=F]

.幂等律
* stem:[p^^p-=p]
* stem:[pvvp-=p]

.双重否定律
* stem:[not(notp)-=p]

.交换律
* stem:[pvvq-=qvvp]
* stem:[p^^q-=q^^p]

.结合律
* stem:[(pvvq)vvr-=pvv(qvvr)]
* stem:[(p^^q)^^r-=p^^(q^^r)]

.分配律
* stem:[pvv(q^^r)-=(pvvq)^^(pvvr)]
* stem:[p^^(qvvr)-=(p^^q)vv(p^^r)]

.否定律
* stem:[pvv(notp)-=T]
* stem:[p^^(notp)-=F]

.吸收律
* stem:[pvv(p^^q)-=p]
* stem:[p^^(pvvq)-=p]

.条件命题的逻辑等价式
* stem:[p->q-=notpvvq]
* stem:[p->q-=notq->notp]
* stem:[pvvq-=notp->q]
* stem:[p^^q-=not(p->notq)]
* stem:[not(p->q)-=p^^notq]
* stem:[(p->q)^^(p->r)-=p->(q^^r)]
* stem:[(p->r)^^(q->r)-=(pvvq)->r]
* stem:[(p->q)vv(p->r)-=p->(qvvr)]
* stem:[(p->r)vv(q->r)-=(p^^q)->r]

.双条件命题的逻辑等价式
* stem:[pharrq-=(p->q)^^(q->p)]
* stem:[pharrq-=notpharrnotq]
* stem:[pharrq-=(p^^q)vv(notp^^notq)]
* stem:[not(pharrq)-=pharrnotq]

=== 谓词和量词

****
stem:[ubrace(AA)_("量词")ubrace(x<0)_("约束论域的量词")ubrace((x^2>0))_("谓词")]
****

> 形式为stem:[P(x_1,x_2,...,x_n)]的语句是命题函数P在n元组stem:[(x_1,x_2,...,x_n)]的值, P也称为n元谓词.

> stem:[P(x)]对于x在其论域中的所有值全为真, 即stem:[P(x)]的全程量化. stem:[AAxP(x)]表示stem:[P(x)]的全称量化, 符号stem:[AA]称为全称量词.

> 论域中存在一个stem:[x]使得stem:[P(x)]为真, 即stem:[P(x)]的存在量化. stem:[EExP(x)]表示stem:[P(x)]的存在量化, 符号stem:[EE]称为存在量词. `全称量词的优先级比存在量词的优先级高`

> 论域中存在唯一一个stem:[x]使得stem:[P(x)]为真, stem:[EE!xP(x)]表示stem:[P(x)]的唯一量化, 符号stem:[EE!]称为唯一量词.

== 离散结构

=== 集合

==== 集合定义

集合是对象的一个无序的聚集, 对象称为集合的元素或成员. 用 stem:[ainA] 表示 a是集合A中的一个元素, 用 stem:[anotinA] 表示 a不是集合A中的一个元素.

==== 描述集合的两种方式

* 花名册法: {a,b,c,d}
* 集合构造器: O={x | x是小于10的所有正整数}

==== 数集

* 自然数: stem:[NN]={0,1,2,3,...}
* 整数集: stem:[ZZ]={...,-1,0,1,2,...}
* 正整数集: stem:[ZZ^+]={1,2,3,...}
* 有理数集合: {stem:[QQ=p/q|p inZ,qinZ且q!=0]}
* 实数集: stem:[RR]
* 正实数集: stem:[RR^+]
* 复数集: stem:[CC]
* 空集: stem:[O/]

==== 子集

集合A是集合B的子集, 当且仅当集合A中的每一个元素都是集合B中的每一个元素. stem:[AAx(x in A -> x in B)].
对于每个非空集合至少有两个子集: 空集和它本身.

真子集: stem:[AAx(x in A -> x in B) ^^ EEx(x in B -> x !in A)]

==== 集合的大小

令S为集合, 如果S中恰有n个不同的元素, 则S是有限集, n为S的基数, 记为 |S|.

==== 幂集

集合S的所有的子集的集合称为S的幂集.
如果一个集合有n个元素, 那它的幂集的基数为 stem:[2^n]

==== 有序n元组

有序n元组stem:[(a_1,a_2,...a_n)]是一个从stem:[a_1]到stem:[a_n]的n个元素的聚集.

==== 笛卡尔积

stem:[AxxB={(a,b)|a in A ^^ b in B}]

==== 带量词的集合符号

* stem:[AAx in S(P(x))] 表示P(x)在集合S上的全称量化.
* stem:[EEx in S(P(x))] 表示P(x)在集合S上的存在量化.

给定谓词P和论域D, 定义P的真值集为D中使P(x)为真的元素x组成的集合. P(x)的真值集记为 stem:[{x in D | P(x)}]

=== 集合运算

* 并集: stem:[AuuB = {x | x in A vv A in B}]
* 交集: stem:[AnnB = {x | x in A ^^ A in B}]
* 差集: stem:[A-B = {x | x in A ^^ A !in B}]
* 补集: stem:[-A={x | x in U ^^ x !in A }]

=== 函数

> 令A和B都是非空集合, 从A到B的函数f是对函数的一种指派, A中每个元素都能指派到B中的一个元素, 写成 f(a)=b.

==== 一对一函数(单射函数)

> 对于函数f的定义域中所有a,b满足 stem:[a!=b->f(a)!=f(b)], 则这个函数是单射的.

==== 映上函数(满射函数)

> 对于函数f的值域中所有b都能满足 f(a)=b, 则这个函数是满射的.

=== 一些重要的函数

* stem:[|__x__|] `向下取整`
* stem:[|~x~|] `向上取整`

=== 序列与求和

==== 几何级数

stem:[f(x)=ar^x]

.求和
* stem:[sum_(j=0)^nar^j={(a*(r^(n+1)-1)/(r-1),r!=1),((n+1)a,r=1):}]
* stem:[sum_(k=1)^nk=(n*(n+1))/2]
* stem:[sum_(k=1)^nk^2=(n*(n+1)*(2n+1))/6]
* stem:[sum_(k=1)^nk^3=(n^2*(n+1)^2)/4]
* stem:[sum_(k=0)^(oo)x^k=1/(1-x), |x|<1]
* stem:[sum_(k=1)^(oo)kx^(k-1)=1/(1-x)^2, |x|<1]

==== 算术级数

stem:[f(x)=ax+b]

=== 矩阵

矩阵是一个矩形状数组, m行n列的矩阵被称为mxn矩阵. m和n相同时被称为方阵.

==== 矩阵运算

* 两个m*n矩阵相加: stem:[A+B=[a_(ij)+b_(ij)]]
* m*k矩阵A和k*n矩阵B相乘: stem:[A*B=[a_(i1)*b_(1j)+a_(i2)*b_(2j)+...+a_(ik)*b_(kj)]]
* 转置: stem:[a_(ij)=b_(ji)]
* 布尔积: stem:[Ao.B=[(a_(i1)^^b_(1j))vv(a_(i2)^^b_(2j))vv...vv(a_(ik)^^b_(kj))]]
* 对称矩阵: stem:[a_(ij)=a_(ji)]

== 计数

=== 基本法则

* 乘积法则: 若一个过程可以被分解为m个任务, 完成第i个任务有stem:[n_i]种方式, 那么完成这个过程有stem:[n_1*n_2*...n_m]种方式.
** 有多少不同的7位位串? stem:[2^7=128]
* 求和法则: 若一个过程可以被分解为m个任务,但这些任务不能同时执行, 完成第i个任务有stem:[n_i]种方式, 那么完成这个过程有stem:[n_1+n_2+...n_m]种方式.
** 一个学生从三个表里选择课题, 这三个表里的课题数量分别为23/15/19, 一共有多少种可能性? stem:[23+15+19=57]
* 减法法则: 如果一个任务可以stem:[n_1]种方法执行或者可以通过stem:[n_2]种方法执行, 那么执行这个任务可以通过stem:[n_1+n_2]种方式减去这两种方式相同的部分.
** 求以1开始或00结束的8位位串数量: stem:[2^7+2^6-2^5=160]
* 除法法则: 如果一个任务能用n种方式实现, 而对于每种方式w,在所有方式中有d种与之对应, 那么完成这个任务有 stem:[n/d] 种独立的方法.

=== 鸽巢原理

> 如果N个物品放入k个盒子, 那么至少有一个盒子里面物品数量至少有 stem:[|~N/K~|].

* 在100个人里面至少有 stem:[|~100/12~|=9]个人出生在同一月.
* 在52张扑克牌中至少选 stem:[(3-1)*4+1=9] 才能保证至少三张牌有同样的花色.
* 在52张扑克牌中至少选 stem:[13*3+3] 才能保证至少三张牌是红心.

=== 排列

一个n元素的r排列数记为 stem:[P(n,r)=n(n-1)(n-2)...(n-r+1)=(n!)/((n-r)!)]

=== 组合

一个n元素的r组合数记为 stem:[C(n,r)=((n),(r))=(n!)/(r!(n-r)!)=C(n,n-r)]

帕斯卡恒等式: stem:[((n+1),(k))=((n),(k-1))+((n),(k))]

n个元素中允许r个重复元素的组合数为 stem:[((n+r-1),(r))]

=== 生成排列

对于给定数列 stem:[a_1a_2a_3...a_n], 从右向左找到 stem:[a_(j-1)<a_j]的两个数, 交换 stem:[a_(j-1)和min(a_j...a_n) && 大于a_(j-1)],
并将 stem:[a_(j+1)到a_n]按字典排序.

=== 生成组合

对于给定数列 stem:[a_1a_2a_3...a_n]的r组合, 找到使得 stem:[a_i!=n-r+i的a_i],将stem:[a_i]加1, 对于
stem:[a_j到a_r (j=i+1)], 用 stem:[a_i+j-i+1]代替 stem:[a_j]

=== 求解线性递推关系

假设 stem:[r^2-c_1r-c_2=0]

* 有两个不相等的根 stem:[r_1和r_2], 那么序列 stem:[{a_n|a_n=a_1r_1^n+a_2r_2^n}]是递推关系 stem:[a_n=c_1a_(n-1)+c_2a_(n-2)]的解.
* 只有一个根 stem:[r_0], 那么序列 stem:[{a_n|a_n=a_1r_0^n+a_2nr_0^n}]是递推关系 stem:[a_n=c_1a_(n-1)+c_2a_(n-2)]的解.

*例1:* stem:[a_n=a_(n-1)+2a_(n-2), a_0=2,a_1=7,求a_n.]

. stem:[r^2-r-2=0 => r={-1,2} => a_n=a_1*(-1)^n+a_2*2^n]
. stem:[{(a_0=2=a_1+a_2),(a_1=7=-a_1+2a_2):} => a_1=-1,a_2=3]
. stem:[a_n=(-1)^(n+1) + 3*2^n]

*例2: 求斐波拉契数列递推关系的解*

. stem:[a_n=a_(n-1)+a_(n-2),a_0=0,a_1=1]
. stem:[r^2-r-1=0, r_1=(1+sqrt5)/2, r_2=(1-sqrt5)/2]
. stem:[{(a_0=0=a_1+a_2),(a_1=1=a_1*(1+sqrt5)/2+a_2*(1-sqrt5)/2):} => a_1=1/sqrt5,a_2=-1/sqrt5]
. stem:[a_n=1/sqrt5*((1+sqrt5)/2)^n-1/sqrt5*((1-sqrt5)/2)^n]

== 关系

=== 二元关系

stem:[AAainAAAbinB((a,b)inR)],称为a与b有关系R.

* 设A和B是集合, 一个从A到B的二元关系是AxB的子集.
* 集合A上的关系是A到A的关系.
* 若 stem:[AAainA((a,a)inR)],则集合R是集合A上的自反关系.
* 对于 stem:[AAaAAbinA,(a,b)inR ^^ (b,a)inR],则集合A上的关系R是对称的.
* 对于 stem:[AAaAAbAAcinA((a,b)inR ^^ (b,c)inR -> (a,c)inR)],集合A上的关系R是传递的.

=== n元关系

