= Elasticsearch
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:hardbreaks:
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 3
:toc-title: 目录
:tabsize: 4
:docinfo: shared

== Elasticsearch介绍

Elasticsearch是一个文档型的NoSQL数据库, 主要用于:

* 实时搜索
* 日志管理
* 数据分析
* 应用监控

== 安装

[source,bash]
----
sudo mkdir -p ~/volumes/es/data0{1..3}/
sudo chmod 777 ~/volumes/es/ -R
----

[source,yaml]
.docker-compose.yml
----
include::https://raw.githubusercontent.com/jjyyjjyy/docker-compose-scratches/master/elk/docker-compose.yml[]
----

== 基本概念

=== 文档

文档以JSON形式存在, 一个文档表示一条数据.
JSON中每个字段都有对应的字段类型 `(boolean/number/string/date/binary/range等)`, 字段类型可以自己指定或者Elasticsearch自动推断.
每个文档都有一个ID, 可以自己指定, 或者Elasticsearch自动生成.

每个文档都有一些元数据字段:

* `_index`: 文档所属的索引名
* `_id`: 文档id
* `_source`: 文档原始JSON数据
* `_version`: 文档版本号
* `_score`: 文档搜索时的评分

=== 索引

表示一类文档的集合.
比如用户索引, 商品索引等.
索引由一个全小写的名称标识, 对文档的CRUD操作均需指定索引名称.
每一个索引都有自己的Mapping, 定义了该索引下文档的字段名和字段类型.

.RDBMS vs Elasticsearch
|===
| RDBMS | Elasticsearch

| Table
| Index

| Row
| Document

| Column
| Field

| Schema
| Mapping

| SQL
| DSL

|===

=== 集群

==== 节点

每个Elasticsearch实例是一个节点, 节点分为:

* master: 可以被选举为master的节点, 执行维护集群状态, 创建/删除索引等操作

[source,properties]
----
node.master: true
node.data: false
node.ingest: false
cluster.remote.connect: false
----

可以设置 `node.voting_only: true` 表示该节点只参与master选举, 但不会成为master.

* data: 处理数据相关操作,比如 CRUD, 全文搜索, 聚合查询等

[source,properties]
----
node.master: false
node.data: true
node.ingest: false
cluster.remote.connect: false
----

* ingest: 负责执行ingest pipeline的节点

[source,properties]
----
node.master: false
node.data: false
node.ingest: true
cluster.remote.connect: false
----

* coordinating: 将请求路由分发到其他节点.

[source,properties]
----
node.master: false
node.data: false
node.ingest: false
cluster.remote.connect: false
----

* ml: 负责执行机器学习Job/处理机器学习请求的节点

[source,properties]
----
node.ml: true
xpack.ml.enabled: true
----

== 文档操作API

=== 创建文档

* POST请求, Elasticsearch会自动生成id

[source,http]
----
POST /users/_doc
{
  "username": "Joan",
  "age": 11
}
----

* PUT请求, 自己指定id

[source,http]
----
PUT /users/_create/1
{
  "age": 33
}
----

第二次请求会报错.

=== 索引文档

[source,http]
----
PUT /users/_doc/1
{
  "username": "Alex",
  "age": 33
}
----

第二次执行后, 会删除原有文档再根据请求体重新创建文档, `_version` 字段加一.

=== 获取文档

[source,http]
----
GET /users/_doc/1
----

=== 更新文档

[source,http]
----
POST /users/_update/1
{
  "doc": {
  "age":111,
  "username": "Bob"
  }
}
----

=== 删除文档

[source,http]
----
DELETE /users/_doc/1
----

=== 批量更新/删除/索引

`bulk` API对索引进行不同的操作.
批量处理过程中单条失败不会影响其他操作, 返回结果也返回了每条操作执行的结果.

[source,http]
----
POST /_bulk
{"create":{"_index":"users","_id":11}}
{"username":"Fatman"}
{"update":{"_index":"users","_id":11}}
{"doc":{"username":"Hollis"}}
{"index":{"_index":"users","_id":11}}
{"username":"Fatman"}
{"delete":{"_index":"users","_id":11}}
----

=== 批量获取

[source,http]
----
GET /_mget
{
  "docs": [
    {
      "_index": "users",
      "_id": 1
    },
    {
      "_index": "users",
      "_id": 2
    }
  ]
}
----

== 倒排索引

倒排索引由两部分组成:

* 单词词典: 记录所有单词, 单词到倒排列表的关系.
* 倒排列表: 记录了单词所处文档的信息:
** 文档id
** 词频 `(TF)`: 记录单词在文档中出现的次数, 用于相关性评分.
** 位置 `(Position)`: 记录单词在文档中分词的位置, 用于语句搜索.
** 偏移 `(Offset)`: 记录单词的开始和结束位置, 用于高亮显示.

=== 倒排索引例子

.源文档
|===
| 文档id | 文档内容

| 1
| Mastering Elasticsearch

| 2
| Elasticsearch Server

| 3
| Elasticsearch Essentials

|===

.Elasticsearch 倒排列表
|===
| 文档id | TF | Position | Offset

| 1
| 1
| 1
| <10,23>

| 2
| 1
| 0
| <0,13>

| 3
| 1
| 0
| <0,13>

|===
