= Elasticsearch
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:hardbreaks:
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 3
:toc-title: 目录
:tabsize: 4
:docinfo: shared

== Elasticsearch介绍

Elasticsearch是一个文档型的NoSQL数据库, 主要用于:

* 实时搜索
* 日志管理
* 数据分析
* 应用监控

== 安装

[source,bash]
----
sudo mkdir -p ~/volumes/es/data0{1..3}/
sudo chmod 777 ~/volumes/es/ -R
----

[source,yaml]
.docker-compose.yml
----
include::https://raw.githubusercontent.com/jjyyjjyy/docker-compose-scratches/master/elk/docker-compose.yml[]
----

== 基本概念

=== 文档

文档以JSON形式存在, 一个文档表示一条数据.
JSON中每个字段都有对应的字段类型 `(boolean/number/string/date/binary/range等)`, 字段类型可以自己指定或者Elasticsearch自动推断.
每个文档都有一个ID, 可以自己指定, 或者Elasticsearch自动生成.

每个文档都有一些元数据字段:

* `_index`: 文档所属的索引名
* `_id`: 文档id
* `_source`: 文档原始JSON数据
* `_version`: 文档版本号
* `_score`: 文档搜索时的评分

=== Term

多个单词形成 `OR` 查询, 不要求顺序.
比如 "Mac OS" 会查询某个字段存在 `Mac` 或 `OS` 的文档.

=== Phrase

多个单词形成短语, 作为一个整体查询.
比如 "Mac OS" 会查询某个字段存在 `Mac OS` 字符串的文档.

=== 索引

表示一类文档的集合.
比如用户索引, 商品索引等.
索引由一个全小写的名称标识, 对文档的CRUD操作均需指定索引名称.
每一个索引都有自己的Mapping, 定义了该索引下文档的字段名和字段类型.

.RDBMS vs Elasticsearch
|===
| RDBMS | Elasticsearch

| Table
| Index

| Row
| Document

| Column
| Field

| Schema
| Mapping

| SQL
| DSL

|===

=== 倒排索引

倒排索引由两部分组成:

* 单词词典: 记录所有单词, 单词到倒排列表的关系.
* 倒排列表: 记录了单词所处文档的信息:
** 文档id
** 词频 `(TF)`: 记录单词在文档中出现的次数, 用于相关性评分.
** 位置 `(Position)`: 记录单词在文档中分词的位置, 用于语句搜索.
** 偏移 `(Offset)`: 记录单词的开始和结束位置, 用于高亮显示.

=== 倒排索引例子

.源文档
|===
| 文档id | 文档内容

| 1
| Mastering Elasticsearch

| 2
| Elasticsearch Server

| 3
| Elasticsearch Essentials

|===

.Elasticsearch 倒排列表
|===
| 文档id | TF | Position | Offset

| 1
| 1
| 1
| <10,23>

| 2
| 1
| 0
| <0,13>

| 3
| 1
| 0
| <0,13>

|===

=== Analysis

文本分析: 把全文本转换为一系列单词的过程, 也叫 _分词_ .
Elasticsearch通过 https://www.elastic.co/guide/en/elasticsearch/reference/current/analyzer-anatomy.html#analyzer-anatomy[Analyser] 实现分词.

Analyser由三部分组成:

* Character filter: 处理原始文本, 比如去除html标签, unicode字符转换等.
* Tokenizer: 将文本切分为多个单词.
* Token filter: 处理切分后的单词, 比如转小写.

[source,http]
.自定义Analyser
----
POST /_analyze
{
  "tokenizer": "standard",
  "char_filter": [{
    "type": "mapping",
    "mappings":["- => _"]
  }],
  "text": ["123-345"]
}
----

=== 集群

==== 节点

每个Elasticsearch实例是一个节点, 节点分为:

* master: 可以被选举为master的节点, 执行维护集群状态, 创建/删除索引等操作

[source,properties]
----
node.master: true
node.data: false
node.ingest: false
cluster.remote.connect: false
----

可以设置 `node.voting_only: true` 表示该节点只参与master选举, 但不会成为master.

* data: 处理数据相关操作,比如 CRUD, 全文搜索, 聚合查询等

[source,properties]
----
node.master: false
node.data: true
node.ingest: false
cluster.remote.connect: false
----

* ingest: 负责执行ingest pipeline的节点

[source,properties]
----
node.master: false
node.data: false
node.ingest: true
cluster.remote.connect: false
----

* coordinating: 将请求路由分发到其他节点.

[source,properties]
----
node.master: false
node.data: false
node.ingest: false
cluster.remote.connect: false
----

* ml: 负责执行机器学习Job/处理机器学习请求的节点

[source,properties]
----
node.ml: true
xpack.ml.enabled: true
----

== 文档操作API

=== 创建文档

* POST请求, Elasticsearch会自动生成id

[source,http]
----
POST /users/_doc
{
  "username": "Joan",
  "age": 11
}
----

* PUT请求, 自己指定id

[source,http]
----
PUT /users/_create/1
{
  "age": 33
}
----

第二次请求会报错.

=== 索引文档

[source,http]
----
PUT /users/_doc/1
{
  "username": "Alex",
  "age": 33
}
----

第二次执行后, 会删除原有文档再根据请求体重新创建文档, `_version` 字段加一.

=== 获取文档

[source,http]
----
GET /users/_doc/1
----

=== 更新文档

[source,http]
----
POST /users/_update/1
{
  "doc": {
  "age":111,
  "username": "Bob"
  }
}
----

=== 删除文档

[source,http]
----
DELETE /users/_doc/1
----

=== 批量更新/删除/索引

`bulk` API对索引进行不同的操作.
批量处理过程中单条失败不会影响其他操作, 返回结果也返回了每条操作执行的结果.

[source,http]
----
POST /_bulk
{"create":{"_index":"users","_id":11}}
{"username":"Fatman"}
{"update":{"_index":"users","_id":11}}
{"doc":{"username":"Hollis"}}
{"index":{"_index":"users","_id":11}}
{"username":"Fatman"}
{"delete":{"_index":"users","_id":11}}
----

=== 批量获取

[source,http]
----
GET /_mget
{
  "docs": [
    {
      "_index": "users",
      "_id": 1
    },
    {
      "_index": "users",
      "_id": 2
    }
  ]
}
----

== URL查询

`GET /<index>/_search`

=== 参数

* q: 查询条件
* df: 查询字段, 如果为空则查询所有字段
* sort: 排序, 格式为 `<field>:[asc|desc]`

[source,http]
----
# 查询存在一个字段包含"Mac"的文档
GET /page_view_info/_search?q=Mac

# 查询ua字段包含"Mac"的文档
GET /page_view_info/_search?q=ua:Mac
GET /page_view_info/_search?df=ua&q=Mac

# 查询ua包含"Mac"或者其他字段包含"Firefox"的文档
GET /page_view_info/_search?q=ua:Mac Firefox

# 查询ua包含"Mac"或者"Firefox"的文档
GET /page_view_info/_search?q=ua:(Mac Firefox)

# 查询ua包含"Mac Firefox"的文档
GET /page_view_info/_search?q=ua:"Mac Firefox"
----

=== 查询条件操作符

==== 布尔操作符

* `AND OR NOT` *必须大写*
* `+ -`

[source,http]
----
# 查询ua包含"Mac"并且包含"Firefox"的文档
GET /page_view_info/_search?q=ua:(Mac AND Firefox)
GET /page_view_info/_search?q=ua:(+Mac AND +Firefox)

# 查询ua包含"Mac"并且但不包含"OS"的文档
GET /page_view_info/_search?q=ua:(Mac NOT OS)
GET /page_view_info/_search?q=ua:(+Mac -OS)
----

==== 范围查询操作符

[source,http]
----
# 查询year大于2018的文档
GET /page_view_info/_search?q=year:>2018

# 查询ua字段存在以"OP"开头的term的文档
GET /page_view_info/_search?q=ua:OP*
----

== Query DSL

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html[]

[source,http]
.DSL查询示例
----
GET /page_view_info/_search
{
  "sort": {"id": "desc"},
  "_source": ["id", "pid", "createdAt"],
  "from": 0,
  "size": 20,
  "query": {}
}
----

=== query_string

[source,http]
----
# 查询ua或os字段包含"Mac"的文档
GET /page_view_info/_search
{
  "query": {
    "query_string": {
      "query": "Mac",
      "fields": ["ua", "os"]
    }
  }
}
----

=== match

[source,http]
----
# 查询ua包含"Mac"并且包含"Firefox"的文档
GET /page_view_info/_search
{
  "query": {
    "match": {
      "ua": {
        "query": "Mac Firefox",
        "operator": "and"
      }
    }
  }
}

----

=== match_phrase

[source,http]
----
# 查询ua包含"Mac Firefox"的文档
GET /page_view_info/_search
{
  "query": {
    "match_phrase": {
      "ua": {
        "query": "Mac Firefox"
      }
    }
  }
}
----

== 聚合查询

Elasticsearch聚合查询分为4种:

* Metric: 对文档字段进行数学运算或统计分析.
* Bucket: 将文档按照条件分组.
* Pipeline: 对聚合结果进行二次聚合.
* Matrix: 对多个字段操作, 结果作为矩阵形式.

=== Metric

==== avg

> 平均值

[source,http]
.计算填单率
----
GET /page_view_info/_search
{
    "aggs": {
      "fillRate": {
        "avg": {
          "field": "fill"
        }
      }
    }
}
----

==== weighted_avg

> 加权平均值: stem:[(sum(weight * value)) / (sum(weight))]

[source,http]
----
GET /page_view_info/_search
{
  "size": 0,
  "aggs": {
    "weightAvgST": {
      "weighted_avg": {
        "value": {
          "field": "lengthOfStay"
        },
        "weight": {
          "field": "fill"
        }
      }
    }
  }
}
----

==== cardinality

> distinct count

[source,http]
.获取uv
----
GET /page_view_info/_search
{
    "aggs": {
      "uv": {
        "cardinality": {
          "field": "uid"
        }
      }
    }
}
----

==== stats

> 统计信息, 包括平均值, 最大值, 最小值, 总和, 次数计数.

[source,http]
.统计停留时长
----
GET /page_view_info/_search
{
    "aggs": {
      "statsST": {
        "stats": {
        "field": "lengthOfStay"
        }
      }
    }
}
----

==== extended_stats

> 详细统计, 包括平均值, 最大值, 最小值, 标准差, 方差, 平方和等维度.

[source,http]
.统计停留时长
----
GET /page_view_info/_search
{
    "aggs": {
      "extendedStatsST": {
        "extended_stats": {
        "field": "lengthOfStay"
        }
      }
    }
}
----

==== max

> 最大值

[source,http]
.获取最大停留时长
----
GET /page_view_info/_search
{
    "aggs": {
      "maxST": {
        "max": {
          "field": "lengthOfStay"
        }
      }
    }
}
----

==== min

> 最小值

[source,http]
.获取最小停留时长
----
GET /page_view_info/_search
{
    "aggs": {
      "minST": {
        "min": {
          "field": "lengthOfStay"
        }
      }
    }
}
----

==== sum

> 求和

[source,http]
.统计填单数
----
GET /page_view_info/_search
{
    "aggs": {
      "fillAmount": {
        "sum": {
          "field": "fill"
        }
      }
    }
}
----

==== value_count

> 计数

[source,http]
.统计pv
----
GET /page_view_info/_search
{
    "aggs": {
      "pv": {
        "value_count": {
          "field": "id"
        }
      }
    }
}
----

==== percentiles

> 百分位

[source,http]
.查看 lengthOfStay
----
GET /page_view_info/_search
{
    "aggs": {
      "stPercentiles": {
        "percentiles": {
          "field": "lengthOfStay"
        }
      }
    }
}
----

==== percentile_ranks

> 数值所处的百分位

[source,http]
----
.查看 lengthOfStay 小于2秒和120秒的百分比
GET /page_view_info/_search
{
    "aggs": {
      "stPercentileRanks": {
        "percentile_ranks": {
          "field": "lengthOfStay",
          "values": [2, 120]
        }
      }
    }
}
----

==== top_hits

> 分组后排序/取前几条记录

[source,http]
----
.查看每个落地页最近10条PV
GET /page_view_info/_search
{
  "size": 0,
  "aggs": {
    "company": {
      "terms": {
        "field": "landingPageId"
      },
      "aggs": {
        "topPV": {
          "top_hits": {
            "_source": ["pid"],
            "sort": [{
              "createdAt": {
                "order": "desc"
              }
            }],
            "size": 10
          }
        }
      }
    }
  }
}
----

=== Bucket

==== term

> 将文档按照指定field分组

[source,http]
----
GET /page_view_info/_search
{
  "size": 0,
  "aggs": {
    "company": {
      "terms": {
        "field": "landingPageId"
      }
    }
  }
}
----

==== range

> 将文档按照范围分组

[source,http]
----
# lengthOfStay按[2,2-60,60-120,120]分组
GET /page_view_info/_search
{
  "size":0,
  "aggs": {
    "st": {
      "range": {
        "field": "lengthOfStay",
        "ranges": [
          {
            "to": 2
          },
          {
            "from": 2,
            "to": 60
          },
          {
            "from": 60,
            "to": 120
          },
          {
            "from": 120
          }
        ]
      }
    }
  }
}
----

==== histogram

> 将文档按照一定的间隔大小分组

[source,http]
----
# accessDepth直方图
GET /page_view_info/_search
{
  "size":0,
  "aggs": {
    "st": {
      "histogram": {
        "field": "accessDepth",
        "interval": 10
      }
    }
  }
}
----

==== filter

> 为某一聚合查询添加过滤条件

[source,http]
----
GET /sales/_search?size=0
{
    "aggs" : {
        "t_shirts" : {
            "filter" : { "term": { "type": "t-shirt" } },
            "aggs" : {
                "avg_price" : { "avg" : { "field" : "price" } }
            }
        }
    }
}
----

==== filters

> 根据条件分组

[source,http]
----
#分别查看公司759和790的PV数量
GET /page_view_info/_search?size=0
{
  "aggs": {
    "landingPages": {
      "filters": {
        "filters": {
          "c759": {
            "bool": {
              "filter": {
                "term": {
                  "companyId": {
                    "value": 759
                  }
                }
              }
            }
          },
          "c790": {
            "bool": {
              "filter": {
                "term": {
                  "companyId": {
                    "value": 790
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
----

==== global

> 使该聚合查询忽略query查询条件

[source,http]
----
#统计759和所有公司的pv
GET /page_view_info/_search?size=0
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "companyId": {
              "value": 759
            }
          }
        },
        {
          "range": {
            "createdAt": {
              "gte": "now/d-60d"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "pv": {
      "value_count": {
        "field": "pid"
      }
    },
    "all_pv": {
      "global": {},
      "aggs": {
        "all_pv": {
          "value_count": {
            "field": "pid"
          }
        }
      }
    }
  }
}
----

==== missing

> 统计没有指定字段的文档数量

[source,http]
----
# 统计没有clickId的文档数量
GET /page_view_info/_search?size=0
{
  "aggs": {
    "missPV": {
      "missing": {
        "field": "clickId"
      }
    }
  }
}
----

==== nested

> 聚合JSON子字段

[source,http]
----
GET /products/_search
{
    "aggs" : {
        "resellers" : {
            "nested" : {
                "path" : "resellers"
            },
            "aggs" : {
                "min_price" : { "min" : { "field" : "resellers.price" } }
            }
        }
    }
}
----

=== Pipeline

==== max_bucket

[source,http]
----
# 找到pv最多的companyId
GET /page_view_info/_search
{
  "size": 0,
  "aggs": {
    "company": {
      "terms": {
        "field": "companyId"
      },
      "aggs": {
        "pv": {
          "cardinality": {
            "field": "id"
          }
        }
      }
    },
    "maxPvCompany": {
      "max_bucket": {
        "buckets_path": "company>pv"
      }
    }
  }
}
----
