= Java
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:hardbreaks:
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 4
:toc-title: 目录
:tabsize: 4
:docinfo: shared

.Resources
* https://book.douban.com/subject/30133440[, window="blank"]
* https://book.douban.com/subject/34907497[, window="blank"]
* https://book.douban.com/subject/26740520[, window="blank"]

== 数据类型

* 基本数据类型
** byte stem:[-2^7 ~ 2*7-1]
** short stem:[-2^15~2^15-1]
** int stem:[-2^31~2^31-1]
** long stem:[-2^63~2^63-1]
** boolean
** char `Unicode` stem:[0~2^16-1]
** float `IEEE754`
** double `IEEE754`

* 引用数据类型
** Class
** Interface
** Array

== 位运算符

* `<<` 左移运算符, 向左移n位, 右边补0.
* `>>` 带符号右移, 向右移n位, 左边补第1位的值.
* `>>>` 无符号右移, 向右移n位, 左边补0.

== 字符编码

=== ASCII

用0~127分别表示128个字符.
1个字节大小

=== Unicode

给每个字符分配一个16进制的数字编号, 数字编号范围从0x000000到0x10FFFF.
但是Unicode本身没有定数字编号到二进制之间的转换关系.

[plantuml,unicode,svg]
....
@startuml
2进制 -> 16进制: UTF-8
2进制 -> 16进制: UTF-16
2进制 -> 16进制: UTF-32
16进制 -> 字符 : Unicode
@enduml
....

==== UTF-8

.UTF-8 使用一至四个字节为每个字符编码
* 对于单字节字符, 首位为0, 后面7位表示字符
* 对于多字节字符, 第一个字节以n个1和一个0开头, 其他字节以10开头, 再从后往前补齐二进制位.

==== UTF-16

.UTF-16 使用二或四个字节为每个字符编码
* 存在一个起始字节序列, `FFFE/FEFF` 标识小端/大端.
* Unicode码小于U+10000的，直接转换为UTF-16双字节序列.
* 大于等于U+10000的, 先减去0x10000, 再分别分成10个比特位.
高位前面用 `110110` 填充, 低位前面用 `110111` 填充.

==== UTF-32

.UTF-32 使用四个字节为每个字符编码
. 存在一个起始字节序列, `0000FEFF/FFFE0000` 分别标识大端/小端.
. 将Unicode码分成四个字节, 高位不足的补0.

|===
| 字符 |Unicode | UTF-8 | UTF-16 | UTF-32

| A
| 00000000,01000001
| 01000001
| 00000000,01000001
| 00000000,00000000,00000000,01000001

| ؆
| 00000110,00000110
| 11011000,10000110
| 00000110,00000110
| 00000000,00000000,00000110,00000110

| 严
| 01001110,00100101
| 11100100,10111000,10100101
| 01001110,00100101
| 00000000,00000000,01001110,00100101

| 𠀲
| 11011000,01000000,11011100,00110010
| 11110000,10100000,10000000,10110010
| 11011000,01000000,11011100,00110010
| 00000000,00000010,00000000,00110010

|===

== 浮点数

=== 浮点数的表示方法

stem:[V=(-1)^s*M*2^E]

* S: 符号位, 决定是正数还是负数, 1代表负数.
* E: 阶码, 值是2的幂, 它的作用是对浮点数加权.
* M: 尾数.

=== 浮点数的存储方法

一个浮点数被分为三部分存储:

* `s` : 符号位标识正数还是负数.
* `exp` : k位阶码字段, 与E相关.Bias=stem:[2^(k-1)-1]
** 单精度为8位.
Bias=127.
** 双精度为11位.
Bias=1023.
* `frac` : n位小数字段, 与M相关.

=== 浮点数的分类

==== 规范化浮点数

[.lead]
`exp` 部分不全为0或1.

E=exp-Bias.
M=frac+1. (规范化浮点数首位为1, 所以M=frac+1)

如 0.10111, 可以表示为 stem:[1.0111* 2^(-1)] , frac=0.0111, M=frac+1=1.0111

==== 非规范化浮点数

[.lead]
`exp` 部分全为0.

E=1-Bias, M=frac.

==== 无穷大

[.lead]
`exp` 部分全为1, `frac` 部分全为0.

==== NaN

[.lead]
`exp` 部分全为1, `frac` 部分不等于0.

== 面向对象

=== 可见性

private << default << protected << public

* `private` : 只能在类的内部访问.
* `default` : 只能被同一个包中其他类访问.
(子包也不能访问)
* `protected` : 可以被子类或同一个包中其他类访问.
* `public` : 可以被任意类访问.

=== 重载

重载指同一个类内方法名称相同, 但方法签名(参数数量/类型)不同.

=== 重写

* 参数列表必须相同.
* 子类可以提升方法的可见性.
* 子类抛出的checked异常必须与父类相同, 或是父类抛出checked异常的子类.
* 子类方法的返回值可以是父类返回值类型的子类.

=== 接口default方法判定

* Class优先.
* 子接口优先.
* 无法确定需用 `类名.super` 显式调用.

NOTE: Class#getDeclaredMethods不包含从父类继承过来的方法.

=== 内部类

==== 静态内部类

静态内部类可以访问外部类的private静态变量和方法, 但不可以访问外部类的实例变量或方法.

==== 成员内部类

* 成员内部类可以访问外部类的实例变量和方法.
* 成员内部类不可以自己定义静态变量和方法.

==== 匿名内部类

匿名内部类方法参数属于final, 不能修改值/引用.

== 异常

=== Checked Exception

继承Exception但不是RuntimeException的异常类.
需要程序手动处理.

=== Unchecked Exception

继承RuntimeException/Error的异常类.
程序可以选择捕获处理, 也可以不处理.

== 注解

=== 重复注解

`@Repeatable(xxx.class) & getAnnotationsByType(xxx.class);`

=== Retention

|===
|   | 源码 | 字节码文件 | 运行时获取

| Source
| √
|
|
| Class
| √
| √
|

| Runtime
| √
| √
| √
|===

=== Target

* Type: 类、接口、注解、枚举
* Field: 字段
* Method: 方法
* Parameter: 方法参数
* Constructor: 构造函数
* Local_Variable: 局部变量
* Annotation_Type: 只能用在注解上
* Package: 包声明上
* Type_Parameter: 类参数, 尚未参透
* Type_Use: 用在任何声明&定义的类型处

== 枚举

=== 枚举类方法

* values() 返回所有枚举常量
* valueOf(String) 返回名字对应的枚举常量
* name() 返回枚举常量名字
* oridinal() 返回枚举常量的序号
* compareTo() 比较枚举常量的序号

=== EnumSet

* EnumSet.allOf(Enum.class) 返回包含所有枚举常量的集合
* EnumSet.rangOf(EnumA,EnumB) 返回A与B之间所有的枚举常量, 包括边界

=== EnumMap

* EnumMap#entrySet 为空,forearch用不了, 只能手动put ==to fix==

== 序列化

. serialVersionUID标识类的序列化的版本号,如果反序列化时当前类的版本号与序列化的二进制流对象的版本号不一致则会抛出异常.
. 序列化时会调用readObject方法,反序列化时会调用writeObject方法.
. 序列化再反序列化后静态成员变量值为最新的.

== 泛型

. 上界通配符 `<? extends T>` 只能get到泛型边界类型
. 下界通配符 `<? super T>` 只能get到Object类型, add时只能传泛型边界的类型.
. 取不到一个类定义的泛型类型(T), 只能取其子类或父类具体的泛型类型(Long,String...).

[source,java]
----
include::../basic-knowledge/src/main/java/me/jy/lang/generic/GenericDemo.java[]
----

== 线程

. 线程状态
* NEW
* RUNNABLE
* BLOCKED
* WAITING
* TIMED_WAITING
* TERMINATED
. 线程内异常无法在外层try-catch,只能设置Thread的UncaughtExceptionHandler
. 每一条线程都有自己的栈空间,拥有一份方法参数、局部变量和返回值的拷贝.每一个线程都有自己的一份标识信息,包括线程名、线程优先级、线程是否存活、线程执行状态、守护线程标识等.
. wait()释放对象锁,sleep()不释放.
. Executor:
* ThreadPoolExecutor
* ForkJoinPool
* ScheduledThreadPoolExecutor
... 如果当前线程池中的线程数目小于corePoolSize，则每来一个任务，就会创建一个线程去执行这个任务；
... 如果当前线程池中的线程数目>=corePoolSize，则每来一个任务，会尝试将其添加到任务缓存队列当中，若添加成功，则该任务会等待空闲线程将其取出去执行；若添加失败（一般来说是任务缓存队列已满），则会尝试创建新的线程去执行这个任务；
... 如果当前线程池中的线程数目达到maximumPoolSize，则会采取任务拒绝策略进行处理；
... 如果线程池中的线程数量大于 corePoolSize时，如果某线程空闲时间超过keepAliveTime，线程将被终止，直至线程池中的线程数目不大于corePoolSize；如果允许为核心池中的线程设置存活时间，那么核心池中的线程空闲时间超过keepAliveTime，线程也会被终止。

=== ThreadPoolExecutor

==== 线程池状态

|===
| 状态名 | 标志 | 是否接收新任务 | 是否处理阻塞队列任务 | 说明

| RUNNING
| 111
| √
| √
|

| SHUTDOWN
| 000
| ×
| √
| 不会接收新的任务, 只会处理阻塞队列中剩余的任务.

| STOP
| 001
| ×
| ×
| 中断正在执行的任务, 抛弃阻塞队列中的任务.

| TIDYING
| 010
| ×
| ×
| 任务全部执行完毕, 活动线程为0, 即将进入终结状态.

| TERMINATED
| 011
| ×
| ×
| 终结状态

|===

==== 使用场景

* FixedThreadPool: 核心线程数等于最大线程数, 使用无界队列存储多余任务, 适用于任务量已知且耗时的场景.
* CachedThreadPool: 没有核心线程数, 适用于任务执行时间短且密集的场景.
* SingleThreadPool: 核心线程数和最大线程数都为1, 适用于希望任务排队串行执行的场景.

== ClassLoader

* loadClass 实现双亲委托模型
* findClass 实现类文件读取

== Stream

[.lead]
一个完整的操作是<数据来源，操作，回调函数>构成的三元组。Stream中使用Stage的概念来描述一个完整的操作，并用某种实例化后的PipelineHelper来代表Stage，将具有先后顺序的各个Stage连到一起，就构成了整个流水线

.中间操作:
. 无状态:
.. unordered
.. filter
.. map
.. mapToInt
.. mapToLong
.. mapToDouble
.. flatMap
.. flatMapToInt
.. flatMapToLong
.. flatMapToDouble
.. peek
. 有状态
.. distinct
.. sorted
.. limit
.. skip

.结束操作
. 非短路操作
.. forEach
.. forEachOrdered
.. toArray
.. reduce
.. collect
.. max
.. min
.. count
. 短路操作
.. anyMatch
.. allMatch
.. noneMatch
.. findFirst
.. findAny

== JDBC

=== Statement

* 同一个connection可以创建多个 `Statement`.
* 在处理 `ResultSet` 的结果时也可以创建另外一个 `Statement`.
* `Statement` 不是线程安全的.
* 用完后需要close.
* SQL语句中如果需要使用包含 `?` 符号的函数可以使用 `??` 转义.

=== ResultSet

* 在获取结果集前需要调用 `next()` 方法.
* 使用 `Statement` 获取 `ResultSet` 后, 当前使用中的 `ResultSet` 会直接关闭.
* 用完后需要close.

== NIO

=== Buffer

Buffer是一个存放基本类型(除了boolean)数据的容器, 拥有以下属性/方法:

* capacity:
容器长度
* limit:
能够写入的长度
* position:
下一个被写入的位置
* flip(): 将position赋值给limit, 再将position设置为0, 重置mark
* rewind(): 将position设置为0, 重置mark
* mark(): 将position赋值给mark
* reset(): 将mark赋值给position

== 多处理器编程

=== 定义

线程A产生一个事件序列 stem:[a_0,a_1,...].
由于线程中往往包含循环, 因此一条程序语句可以产生多次事件.
用 stem:[a_i^j] 表示事件 stem:[a_i] 的第 stem:[j] 次发生. 如果事件a在事件b之前发生, 则称a先于b, 记作 stem:[a->b] .

令 stem:[a_0,a_1]表示事件, 且 stem:[a_0->a_1], stem:[I_A] =interval( stem:[a_0->a_1] )表示 stem:[a_0和a_1] 事件之间的间隔.
如果 stem:[a_1->b_0],则 stem:[I_A->I_B].多个不存在 stem:[->]的关系称为 *并发的*.

* *互斥*: 对于线程A,B, 以及整数j,k, 都有 stem:[CS_A^j->CS_B^i]或者stem:[CS_B^j->CS_A^i].
* *无死锁*: 如果一个线程正在尝试获得一个锁, 那么总会成功地获取到锁.
如果暂时无法获得, 那么一定存在其他线程已经进入临界区.
* *无饥饿*: 每个尝试获得锁的线程最终都能成功.
(无饥饿意味着无死锁)

=== 互斥

[source,java]
.Lock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/Lock.java[]
----

==== 双线程实现互斥

[source,java]
.LockOne.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/LockOne.java[]
----

[source,java]
.LockTwo.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/LockTwo.java[]
----

[source,java]
.PetersonLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/PetersonLock.java[]
----

==== 多线程实现互斥

[source,java]
.FilterLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/spin/FilterLock.java[]
----

[source,java]
.BakeryLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/spin/BakeryLock.java[]
----

=== 内存访问

处理器和存储控制器之间通过总线通信, 同一时间只能有一个处理器在总线上广播, 但处理器可以和存储控制器同时广播.
所有的处理器都可以监听.
每一个处理器都有一个cache. 当处理器想从存储器读数据时, 首先检查该内存地址以及值是否已经在cache中. 如果在cache中, 那么处理器可以产生一个cache命中, 立即加载这个值.
如果不在, 则产生一个 `cache miss` , 紧接着在总线上广播这个地址, 其他的处理器监听总线, 如果某个处理器在自己的cache中发现这个地址, 则广播该地址及其值做出响应.
如果所有的处理器都没有发现该地址, 则从内存中加载.

=== 自旋锁

多线程竞争临界区, 如果不能获得锁, 有两种选择:

* 让其继续尝试, 称为 *自旋锁* .
* 挂起自己, 请求操作系统调度另外一个线程, 称为 *阻塞* .

许多操作系统将这两种结合起来使用, 先旋转一个小的时间段再阻塞.

==== TestAndSet

[source,java]
.TASLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/spin/TASLock.java[]
----

.TAS缺点:
* 每个 `getAndSet` 对应总线上一次广播, 该广播会延迟所有的线程, 包括那些没有阻塞锁和准备释放锁的线程.
* `getAndSet` 设置值后会导致所有处理器丢弃 `cache` .

==== TestAndTestAndSet

[source,java]
.TTASLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/spin/TTASLock.java[]
----

.TTAS改进:
* 自旋时只会读取本地的cache值, 不产生总线流量.

==== Backoff TestAndTestAndSet

[source,java]
.Backoff.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/Backoff.java[]
----

[source,java]
.TTASBackoffLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/spin/TTASBackoffLock.java[]
----

.TTASBackoffLock改进:
* 当有其他线程释放锁, 但当前线程没有竞争到锁后会后退一个随机的时间间隔再去争用锁, 减少CPU消耗.

==== 队列锁(数组)

[source,java]
.ArrayLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/spin/ArrayLock.java[]
----

==== 队列锁(CLH)

[source,java]
.CLHLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/spin/CLHLock.java[]
----

==== 队列锁(MCS)

[source,java]
.MCSLock.java
----
include::../basic-knowledge/src/main/java/me/jy/lang/thread/lock/spin/MCSLock.java[]
----

== JVM

=== JVM概述

JVM是一个支持在不同操作系统上执行Java字节码的运行时容器, 拥有内存管理/垃圾回收等功能.
Java字节码无法直接执行, JVM需要将其翻译成机器码.
在HotSpot里, 该翻译过程有两种形式:

* 解释执行: 逐条将字节码翻译成机器码.
* 即时编译执行: 将一个方法中所有的字节码翻译成机器码后再执行.

HotSpot内置多种编译器:

* `C1` 启动块,编译时间短
* `C2` 编译时间比较长,但执行效率高
* `graal`

=== Class文件组成

* magic number
* minor&major versions
* constant pool
* access flags
* this class
* super class
* interfaces
* fields
* methods
* attributes

=== 类加载器

==== 获取类加载器的方法

* `Class::getClassLoader()`
* `Thread.currentThread().getContextClassLoader()`
* `ClassLoader.getSystemClassLoader()`

==== BootstrapClassLoader

启动类加载器.
本身使用C/C++实现, 没有父加载器.
通过 `sun.misc.Launcher.getBootstrapClassPath().getURLs()` 获取加载类的路径.

==== ExtClassLoader

加载jre/lib/ext子目录下的类库, 父加载器为BootstrapClassLoader.
通过 `System.getProperty("java.ext.dirs")` 获取加载类的路径.

==== AppClassLoader

加载classpath/java.class.path路径下的类库, 是应用程序默认的类加载器.
父加载器为ExtClassLoader.

==== 用户自定义类加载器

.为什么要自定义类加载器?
* 修改类加载的方式.
* 隔离加载类.
* 扩展加载源.
* 防止源码泄露.

.实现自定义类加载器的方式
* 继承 `ClassLoader` 类, 覆盖 `findClass()` 方法.
* 继承 `URLClassLoader` 类.

==== 双亲委派机制

[.lead]
加载某个类的class文件时, 把请求委托给父加载器处理.
如果父加载器无法加载, 则子加载器才会自己去加载.

.优点
* 避免类的重复加载.
* 防止jdk核心类的篡改.

=== 类加载的过程

==== 加载

. 通过一个类的全限定名获取定义此类的二进制字节流.
. 将这个字节流所代表的的静态存储结构转化为方法区的运行时数据结构.
. 在内存中生成一个代表这个类的 `java.lang.Class` 对象, 作为方法区这个类的各种数据的访问入口.

==== 链接

链接分为 _验证, 准备, 解析_ 三个阶段.

.验证
确保字节流符合当前虚拟机要求, 保证类加载的正确性.
验证文件格式/元数据/字节码/符号引用.

.准备
为静态变量分配零值(null/0).
常量设置初始值.

.解析
解析符号引用为直接引用.

==== 初始化

执行类构造器方法 `clinit()` , 该方法是由javac编译器自动收集类中的所有类变量的赋值动作和静态代码块中的语句合并而来.

.触发类初始化的条件
* 创建类的实例.
* 访问类的静态变量, 或者对该变量赋值.
* 调用类的静态方法.
* 反射. `Class.forName("FQCN")`
* 加载一个类的子类.
* JVM启动时作为启动入口的类.
* 通过MethodHandler解析的类.

=== JVM内存布局

[plantuml,jvm-memory,svg]
....
@startuml
package "JVM内存布局" {
  [方法区] #Red
  [程序计数器] #Gray
  [本地方法栈] #Gray
  [堆] #Red
  [虚拟机栈] #Gray
}
@enduml
....

红色代表线程共享, 灰色代表线程私有.

==== PC

存储下一条要执行的指令的地址.
如果在执行的是native方法, 则值为undefined.

==== 虚拟机栈

每个线程在创建时都会创建一个虚拟机栈, 栈中的数据以栈帧的格式存在.
在这个线程上执行的每个方法都各自对应一个栈帧.
栈顶的栈帧对应的就是当前正在执行的方法, 如果该方法调用了其他方法, 则创建出一个新的栈帧并入栈.
方法执行完或抛出异常时当前栈帧会出栈.

.栈帧组成
* 局部变量表(方法内部局部变量字节码行号和变量名的映射关系.)
* 操作数栈(在方法执行过程中保存计算结果的临时存储空间. 操作数栈的大小 `max_stack` 在编译时就会确定好, 保存在方法的Code属性中.)
* 动态链接(指向运行时常量池的方法引用.)
* 方法返回地址(存放调用该方法的pc寄存器的值.)
* ...

线程请求分配的栈容量超过JVM允许的最大容量, JVM会抛出 `StackOverflowError` .
如果Java虚拟机栈在尝试扩展的时候申请不到足够的内存, 或者创建新的线程时没有足够的内存去创建对应的虚拟机栈, JVM会抛出 `OutOfMemoryError` .

[source,java]
.StackOverflowError
----
include::../jvm/src/test/java/OOMDemo.java[tag=StackOverflow]
----

[source,java]
.OutOfMemoryError
----
include::../jvm/src/test/java/OOMDemo.java[tag=StackOOM]
----

==== 本地方法栈

管理本地方法的调用.

==== 方法区

==== 堆

=== JDK常用工具

==== jcmd

打印Java进程所涉及的基本类, 线程和VM信息

`jcmd <pid> <command> [args]`

* `jcmd 9914 VM.system_properties` 查看JVM进程properties
* `jcmd 9914 VM.uptime` 查看JVM进程运行时间
* `jcmd 9914 VM.version` 查看JVM版本
* `jcmd 9914 VM.command_line` 查看JVM启动命令
* `jcmd 9914 VM.flags` 查看JVM启动参数
* `jcmd 9914 Thread.print` 查看JVM线程栈信息

==== jps

查看系统运行的所有Java进程的pid

`jps -l`

==== jinfo

查看指定Java进程信息

`jinfo [option] <pid>`

* `jinfo -flags 1` 查看pid为1的进程的所有启动参数
* `jinfo -flag UseCompressedOops 9914` 查看指定参数

==== jstack

查看指定Java进程中每个线程栈信息

`jstack <pid>`

==== jstat

查看指定进程的内存概况. 如: jstat -gcutil 1 1000 每隔1秒输出1进程的概况

`jstat [option] <pid> [interval]`

.各列含义
* `S0` 第一个survivor区容量
* `S1` 第二个survivor区容量
* `E` Eden区容量
* `O` Old区容量
* `M` Metaspace区容量
* `YGC` young gc次数
* `YGCT` young gc总耗时
* `FGC` full gc次数
* `FGCT` full gc总耗时
* `GCT` gc总耗时

==== javap

查看class字节码文件

`javap <class file>`

* -c: 反编译class
* -p: 显示 `private` 方法和字段
* -v: 显示详细信息
* -s: 显示类型签名
* -l: 输出行号和本地变量表
* -sysinfo: 显示类的系统信息

=== JVM参数

==== 参数分类

JVM主要接受两类标志: boolean类和赋值类参数.

* boolean类:
`-XX:+FLAG_NAME`.
如: `-XX:+UseCompressedOops` 开启64位JVM中的对象引用压缩,`-XX:-UseCompressedOops` 关闭压缩.

* 赋值类: `-XX:+FLAG_NAME=VALUE`.
如 `-XX:AutoBoxCacheMax=20000`.

* 简写类.
如 `-Xms -Xmx -Xmn -Xss`

TIP: 查看所有可选标志: `java -XX:+PrintFlagsFinal -version`

==== 常用启动参数

.GC收集器选择类
* `-XX:+UseSerialGC` 使用Serial+Serial Old组合回收新生代和老年代.
* `-XX:+UseParNewGC` 使用ParNew+Serial Old组合回收新生代和老年代.
* `-XX:+UseConcMarkSweepGC` 使用ParNew+CMS组合回收新生代和老年代, 当出现 _Concurrent Mode Failure_ 后使用Serial Old回收老年代.
* `-XX:+UseParallelGC` 使用Parallel Scavenge+Serial Old组合回收新生代和老年代.
* `-XX:+UseParallelOldGC` 使用Parallel Scavenge+Parallel Old组合回收新生代和老年代.
* `-XX:+UseG1GC` 使用G1回收堆内存.
* `-XX:+UseZGC` 使用ZGC回收堆内存.
* `-XX:+UseShenandoahGC` 使用ShenandoahGC回收堆内存, 只能在OpenJDK12及以上版本中使用.

.Java8及以下GC日志输出类
* `-XX:+PrintGC` 输出GC简要日志.
* `-XX:+PrintGCDetails` 输出gc详细日志.
* `-XX:+PrintHeapAtGC` 输出GC前后堆和方法区容量大小.
* `-XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCApplicationStoppedTime` 输出GC与用户线程并发时间以及GC停顿时间.
* `-XX:+PrintAdaptiveSizePolicy` 查看JVM堆各个分代大小自动调节信息.
* `-XX:+PrintTenuringDistribution` 查看GC后剩余对象的年龄分布信息.
* `-Xloggc:<FILENAME> -XX:+UseGCLogfileRotation -XX:NumberOfGCLogfiles=N -XX:GCLogfileSize=N` gc日志写入指定文件并切割.

.Java9及以下GC日志输出类 `-Xlog[:[selector][:[output][:[decorators][:output-options]]]]`
* `-Xlog:gc` 输出GC简要日志.
* `-Xlog:gc*` 输出GC详细日志.
* `-Xlog:gc+heap=debug` 输出GC前后堆和方法区容量大小.
* `-Xlog:safepoint` 输出GC与用户线程并发时间以及GC停顿时间.
* `-Xlog:gc+ergo*=trace` 查看JVM堆各个分代大小自动调节信息.
* `-Xlog:gc+age=trace` 查看GC后剩余对象的年龄分布信息.
* `-Xlog:gc*:file=<file>::filecount=<count>,filesize=<sizekb>` gc日志写入指定文件并切割.

.GC性能类
* `-XX:SurvivorRatio=8` 新生代中 _Eden_ 区和 _Survivor_ 区的比例, 默认为8, 及 8:1:1 .
* `-XX:PretenureSizeThreshold=0` 直接晋升到老年代的对象大小, 大于这个参数的对象将直接在老年代上分配.
* `-XX:MaxTenuringThreshold=15` 晋升到老年代的对象年龄.
每个对象在 _Minor GC_ 后年龄加一, 当年龄超过这个参数后会进入老年代.
* `-XX:+UseAdaptiveSizePolicy` 动态调整堆中各个区域的大小以及老年代的年龄.
* `-XX:ParallelGCThreads=8` 设置并行GC时进行内存回收的线程数.
* `-XX:GCTimeRatio=N` 设置应用运行时间占比: stem:["Throughput"="GCTimeRatio"/(1+"GCTimeRatio")]
* `-XX:MaxGCPauseMillis=N` 设定应用可承受的最大停顿时间.一般设置为200, 如果设置的值过小, 会导致老年代非常小, 从而频繁进行 _Full GC_ .
* `-XX:CMSInitiatingOccupancyFraction=68` 设置CMS收集器在老年代空间被使用多少后触发垃圾回收, 默认为68%.
* `-XX:+UseCMSCompactAtFullCollection` 设置CMS在 _Full GC_ 后是否进行内存碎片整理. [Java9后废弃]
* `-XX:CMSFullGCsBeforeCompaction=0` 设置CMS在多少次 _Full GC_ 后进行内存碎片整理. [Java9后废弃]
* `-XX:G1HeapRegionSize=0` 设置G1 Region大小.
* `-XX:G1NewSizePercent=5` 设置G1新生代最小值, 默认为5%.
* `-XX:G1MaxNewSizePercent=60` 设置G1新生代最大值, 默认为60%.
* `-XX:InitiatingHeapOccupancyPercent` 设置触发标记周期的堆(old+humongous)占用阈值, 默认为45%.

=== 内存分配策略

==== 对象优先在Eden区分配

大多数情况下, 对象在新生代Eden区中分配.
当Eden区没有足够空间进行分配时, 虚拟机将发起一次 _Minor GC_ .

==== 大对象直接进入老年代

需要大量连续内存空间的Java对象(如数组), 直接在老年代分配.
虚拟机提供了 `-XX:PretenureSizeThreshold` 参数指定大于该参数值的对象直接在老年代分配.

==== 长期存活的对象进入老年代

对象如果在 _Minor GC_ 后仍然存活, 并能被Survivor区容纳, 则移动到Survivor区, 年龄加1. 年龄超过 `MaxTenuringThreshold` 参数后, 下次 _Minor GC_ 时会进入老年代.

==== 老年代空间分配担保

_Minor GC_ 之前, 虚拟机会先检查老年代最大可用的连续空间是否大于等于新生代所有对象总空间或者大于等于历史晋升的平均大小, 如果大于则进行 _Minor GC_ , 否则将直接进行 _Full FC_ .

=== 垃圾收集算法

==== 复制

将内存按容量划分为大小相等的两块, 每次只用其中的一块.
当某一块的内存用完了, 就将还存活的的对象复制到另外一块上, 然后再把已使用过的内存空间一次清理掉.

.优点
* 为对象分配内存时不需要考虑内存碎片的问题.

.缺点
* 可用内存只有一半.
* 如果对象的存活率高, 则拷贝对象的操作开销比较大.

.使用场景
* Serial/ParNew收集器使用复制算法收集新生代.

==== 标记整理

让所有存活的对象向内存空间一端移动, 然后直接清理掉边界以外的内存.

.优点
* 没有内存碎片

.缺点
* 移动对象的开销大.

.使用场景
* Serial Old/Parallel Scavenge使用标记-整理算法收集老年代.

==== 标记清除

首先标记出所有需要回收的对象, 在标记完成后统一回收所有被标记的对象.

.优点
* 相对于复制算法节省了内存空间.

.缺点
* 执行效率不稳定, 如果内存中大量对象需要被回收, 则必须进行大量标记和清除的动作.
* 导致内存碎片化.

.使用场景
* CMS使用标记清除算法回收老年代.

=== 垃圾收集器

[.lead]
垃圾收集分两步: 在为对象分配内存时遇到内存不足, 查找不再使用的对象, 然后释放这些对象所在的内存.

由于对象的生存时间不同, 所有的垃圾收集器都采用分代收集的方式.
堆内存被划分为 *新生代* (Young Generation)和 *老年代* (Old Generation或Tenured Generation), 默认空间占比 1:2. 新生代又被分为一个Eden区和两个Survivor区.
默认空间占比 8:1:1.

对象首先在新生代Eden区分配, *Eden区填满时*, 垃圾收集器会暂停所有应用线程回收新生代(垃圾收集时所有应用线程停止运行所产生的停顿称为 **STW**(stop-the-world)).此时不再使用的对象会被回收, 仍在使用的对象会移动到Survivor区或老年代.
这一过程称为 *Minor GC*.
由于所有的存活对象都被移走, 此时相当于在新生代做了一次整理.
单独回收老年代的过程称为 *Major GC*.
(CMS) 回收新生代和一部分老年代的过程称为 *Mixed GC*.(G1) 对象不断移动到老年代, 等到 *老年代空间占满*, JVM会回收整个堆.
这一过程称为 *Full GC*.

==== Serial

[.lead]
Serial垃圾收集器使用单线程回收内存, 垃圾回收时会暂停所有的应用线程.
使用 `-XX:+UseSerialGC` 启用Serial垃圾收集器.

==== Parallel

TIP: JDK8默认收集器

[.lead]
Parallel垃圾收集器使用多线程回收内存, 垃圾回收时会暂停所有的应用线程.
使用 `-XX:+UseParallelGC` 启用Parallel垃圾收集器.

==== CMS

[.lead]
CMS回收新生代时会暂停所有应用线程, 使用多线程回收.
在Full GC时不再暂停应用线程, 而是使用若干个后台线程定期扫描老年代, 及时回收不再使用的对象.
但是当堆变得碎片化, CMS会退化成Serial收集器使用单线程回收内存并整理老年代, 之后再恢复成多线程收集.
使用 `-XX:+UseConcMarkSweepGC` 启用CMS收集器.

==== G1

TIP: JDK9默认收集器

使用 `-XX:+UseG1GC` 启动G1收集器

==== ZGC

使用 `-XX:+UseZGC` 启动ZGC收集器

=== GC调优

==== 选择恰当的垃圾收集器

* 数据分析/科学计算类应用, 关注吞吐量.
* 事务型应用, 关注低延迟.
* 客户端/嵌入式设备应用, 关注内存占用.

==== 永远不要把堆内存的大小设置的比机器物理内存大

 Full GC时JVM会访问整个堆的内容, 内存交换会拖慢GC的速度. 使用-Xms和-Xmx分别设置堆内存的最小值和最大值.
 默认64位JVM堆内存初始值为取512MB和物理内存大小1/64二者中的最小值, 最大值取32G和物理内存大小1/4二者中的最小值.

==== 调整新生代与老年代的大小

.新生代大小设置参数, 后者优先级更高
** -XX:NewRatio 设置新生代与老年代的比例, 默认值为2. 默认情况下新生代大小初始值等于 `初始堆大小/(1+NewRatio)`
** -XX:NewSize 设置新生代大小的初始值
** -XX:MaxNewSize 设置新生代大小的最大值
** -Xmn 同时设置新生代的初始值和最大值

推荐设置: `-XX:NewRatio=4`

=== gc日志分析

==== Parallel Minor GC

[source,txt]
----
2018-07-25T10:15:43.831+0000: 7.861: [GC (Metadata GC Threshold)
Desired survivor size 178782208 bytes, new threshold 7 (max 15)
[PSYoungGen: 1284666K->30929K(1958400K)] <1>
 1314750K->61020K(4754944K), <2>
  0.0605807 secs] [Times: user=0.31 sys=0.02, real=0.06 secs] <3>
----
<1> 新生代的空间使用从1284MB降到30MB, 此时整个新生代大小为1958MB.
<2> 整个堆的空间使用从1314MB降到61MB.
<3> 本次gc花费0.06秒(并行回收), 总共消耗CPU的时间为0.31秒.

==== Parallel Full GC

[source,txt]
----
2018-07-25T10:15:39.817+0000: 3.847: [Full GC (Metadata GC Threshold)
[PSYoungGen: 25798K->0K(1450496K)] <1>
[ParOldGen: 12907K->30083K(2796544K)] <2>
38705K->30083K(4247040K), <3>
[Metaspace: 33973K->33973K(1081344K)], 0.0771380 secs] <4>
[Times: user=0.40 sys=0.01, real=0.07 secs] <5>
----
<1> 新生代的占用空间从25MB降到0, 此时整个新生代大小为1450MB.
<2> 老年代的占用空间从12MB升到30MB, 此时整个老年代大小为2796MB (此时老年代经过了压缩整理).
<3> 整个堆的空间占用从38MB降到30MB, 此时整个堆的大小为4247MB.
<4> Metaspace没有回收.
<5> 本次回收用时.0.7秒, 总消耗CPU时间0.4秒.

==== CMS垃圾收集器

[source,java]
----
// -Xmx20M -Xms20M -Xmn10M -verbose:gc -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC
public class MemoryTest {

    private static final int MB = 1024 * 1024;

    public static void main(String[] args){
        byte[] b1 = new byte[MB];
        byte[] b2 = new byte[2 * MB];
        byte[] b3 = new byte[3 * MB];
        byte[] b4 = new byte[4 * MB];
        byte[] b6 = new byte[2 * MB];
        byte[] b7 = new byte[3 * MB];
    }
}
----

==== ParNew Minor GC

[source,text]
----
[GC (Allocation Failure) [ParNew: 7819K->518K(9216K), 0.0044298 secs] <1>
7819K->6664K(19456K), 0.0044645 secs] <2>
[Times: user=0.02 sys=0.00, real=0.00 secs] <3>
----
<1> 新生代的占用空间从78MB降到5MB, 此时整个新生代大小为92MB.
<2> 整个堆的空间占用从78MB降到66MB, 此时整个堆的大小为20MB.
<3> 本次GC用时0.001秒, 总消耗CPU时间0.02秒.

== QA

[qanda]
`|` 和 `||` 的区别?::
`||` 是短路操作, 如果左边是true, 则右边不会执行. `|` 左右两边都会执行.
`ClassLoader.loadClass()` 和 `Class.forName()` 有什么区别?::
`Class.forName()` 会初始化类的static代码块和static参数, `ClassLoader.loadClass()` 不会.
`ClassNotFoundException` 和 `NoClassDefFoundError` 有什么区别?::
* `ClassNotFoundException` 是Exception类型, `NoClassDefFoundError` 是Error类型.
* 使用 `Class.forName()` / `ClassLoader.loadClass()` / `ClassLoader.findSystemClass()` 动态加载类时找不到类就会抛出 `ClassNotFoundException` ,当编译成功但运行时(调用该类的一个方法或者new一个实例时)找不到类或者初始化static成员时有异常则会抛出 `NoClassDefFoundError` 异常.
强引用/软引用/弱引用/虚引用区别及使用场景?::
* 普通对象被其他对象引用, 这样的引用为强引用.
* JVM在内存不足时回收软引用
* TODO
泛型的 `PECS` 原则?::
* Producer Extends: 设计的类是生产者, 用 `extends`
* Consumer Super: 设计的类是消费者, 用 `super`
创建对象方式?::
* new
* Object.clone()
* Class#newInstance()
* 反序列化
* Unsafe.allocateInstance
如何找到JVM CPU占用高的原因?::
. `jps` 查看JVM进程 `PID`.
. `top -Hp PID` 查看该JVM进程内线程资源占用情况.找到占用资源高的线程 `TID`.
. `printf '%x\n' TID` 将线程id转成16进制数.
. `jstack PID | grep TID -A 10` 查看该线程所在堆栈, 检查堆栈所在代码上的错误.
Java中Connection为什么要close?::
及时释放数据库链接, 减少资源消耗. (如果没有显式close, 也会被gc)
