= Mybatis
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:source-linenums-option:
:hardbreaks:
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 3
:toc-title: 目录
:tabsize: 4
:docinfo: shared

== 核心类

=== TransactionFactory

[plantuml,TransactionFactory,svg]
....

interface TransactionFactory {
    + Transaction newTransaction()
}

TransactionFactory <.. JdbcTransactionFactory
TransactionFactory <.. ManagedTransactionFactory

note bottom of JdbcTransactionFactory
* 创建JdbcTransaction对象, 使用JDBC API管理数据库连接的生命周期.
end note

note bottom of ManagedTransactionFactory
* 创建ManagedTransaction对象, 让外部容器管理数据库连接.
end note

....

=== DataSource

[plantuml,DataSource,svg]
....

interface DataSource {
}

DataSource <.. PooledDataSource
DataSource <.. UnpooledDataSource

note bottom of UnpooledDataSource
* 每次使用DriverManager建立数据库连接.
end note

note bottom of PooledDataSource
* 简易数据库连接池
end note

....

=== Environment

[plantuml,Environment,svg]
....

class Environment {
  - String id
  - TransactionFactory transactionFactory
  - DataSource dataSource
}

note bottom: 维护一个环境的 transactionFactory 和 dataSource 对象.

....

=== Configuration

[plantuml,Configuration,svg]
....

class Configuration {
}

note bottom: 维护Mybatis全局配置信息.

....

=== SqlSessionFactory

[plantuml,SqlSessionFactory,svg]
....

interface SqlSessionFactory {
  + SqlSession openSession()
}

SqlSessionFactory <.. DefaultSqlSessionFactory
SqlSessionFactory <.. SqlSessionManager
SqlSessionFactory <-- SqlSessionManager

note bottom of DefaultSqlSessionFactory: 创建 Executor & SqlSession, 执行Mapper方法.
note bottom of SqlSessionManager: 使用外部自定义的SqlSessionFactory.

....

=== MapperMethod

[plantuml,MapperMethod,svg]
....

class MapperMethod {
  - SqlCommand command
  - MethodSignature method
}

note bottom: 封装Mapper方法使用SqlSession执行操作.

class SqlCommand {
  - String name
  - SqlCommandType type
}

class MethodSignature {

    - boolean returnsMany
    - boolean returnsMap
    - boolean returnsVoid
    - boolean returnsCursor
    - boolean returnsOptional
    - Class<?> returnType
    - String mapKey
    - Integer resultHandlerIndex
    - Integer rowBoundsIndex
    - ParamNameResolver paramNameResolver
}

enum SqlCommandType {
  UNKNOWN
  INSERT
  UPDATE
  DELETE
  SELECT
  FLUSH
}

....

=== Executor

[plantuml,Executor,svg]
....

interface Executor {
}

Executor <.. CachingExecutor
Executor <.. ReuseExecutor
Executor <.. BatchExecutor
Executor <.. SimpleExecutor

....
