= Postgresql
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:sectlinks:
:toc: left
:toclevels: 3
:toc-title: 目录

== 1. 安装

=== 1.1 docker
[source,bash]
.docker-compose.yml
----
version: '3'
services:
    postgresql:
        image: postgres:10.5-alpine
        container_name: postgresql
        volumes:
            - ~/volumes/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jy
            - POSTGRES_PASSWORD=123456
            - TZ=Asia/Shanghai
        ports:
            - 5432:5432
        networks:
            - postgresql

networks:
    postgresql:
----
=== 1.2 安装包安装

[source,bash]
----
groupadd postgres
useradd postgres -g postgres
passwd postgres
mkdir -p /database/pg10/pg_root
chown -R postgres:postgres /database/pg10

sudo apt install postgresql-all
initdb -D /database/pg10/pg_root -E UTF8 --locale=C -U postgres -W
----




== 2. 基本命令
[source,bash]
----
# 创建db
createdb -U <username> <dbName>
# 删除b
dropdb -U <username> <dbName>
# 重建索引
reindexdb -d <dbName>
# 对数据库物理文件垃圾回收
vacuumdb <dbName>
# 清除数据库中未引用的大对象
vacuumlo <dbName>

pgdump
pgrestore
pgbench
# 登录数据库
psql [-h HOST] [-p PORT] DB [USERNAME]
# 获取pg配置
pg_config
# 获取数据库状态
pg_ctl -D <data-dir> status
# 启动数据库
postgres -D <data-dir> &
# 关闭数据库
pg_ctl -D <data-dir> -m [fast|smart|immediate]  -t <timeout> stop
----

== 3. 配置

=== 3.1 pg_hba.conf

[source,bash]
----
TYPE  DATABASE  USER  ADDRESS  METHOD
----

* TYPE: 允许连接的方式
  ** local: Unix domain socket
  ** host:  TCP/IP, localhost default
  ** hostssl: OpenSSL restrict
  ** hostnossl: SSL not permitted
* METHOD: 认证方法
  ** trust
  ** password: 明文密码
  ** md5
  ** reject: 拒绝访问
  ** scram-sha-256

=== 3.2 postgresql.conf

 postgresql 启动时postgresql.auto.conf会覆盖postgresql.conf内容
 更改配置生效: pg_ctl -D <data-dir> reload

== 4. psql命令

* psql -c "SQL" [-d DB_NAME] [-U USERNAME] [-W PASSWORD] [-f SQL_FILE]
* \db: 查看表空间
* \l: 查看数据库
* \d <DB_NAME>: 查看表定义
* \dt+ <DB_NAME>: 查看表空间大小
* \di+ <IDX_NAME>: 查看索引空间大小
* \x: 切换查询显示模式
* COPY <DB> FROM|TO "FILE_PATH" : (大表)导入导出数据(必须有superuser权限)
* \copy <DB> FROM|TO "FILE_PATH" : (小表)导入导出数据
* \set VAR_NAME VALUE: 设置变量, :VAR_NAME 使用
* \timing: 开启sql计时

== 5. Monitor

[source,sql]
----
-- 查看活动会话
select pid, usename, datname, query, client_addr
from pg_stat_activity
where pid <> pg_backend_pid()
  and state = 'active'
order by query;

-- 查看会话等待事件
select pid, usename, datname, query, client_addr, wait_event_type, wait_event
from pg_stat_activity
where pid <> pg_backend_pid()
  and wait_event is not null
order by wait_event_type;

-- 查看数据库等待数
select datname, usename, client_addr, count(*)
from pg_stat_activity
where pid <> pg_backend_pid()
group by 1, 2, 3
order by 1, 2, 4 desc;

----

== 6. 数据类型

=== 6.1 数字类型
* int2 int4 int8
* decimal/numeric[(precision,scale)]
* real 6位十进制精度浮点数
* double precision 15位十进制精度浮点数
* smallserial/serial/bigserial 2/4/8字节自增序列

=== 6.2 字符串类型
* varchar/character varying 变长
* character/char 定长
* text 变长,无长度限制

=== 6.3 日期类型
* timestamp[without time zone]
* timestamp[with time zone] / timestamptz
* date
* time[with[out] time zone]
* interval

=== 6.4 range类型
* int4range
* int8range
* numrange
* tsrange
* tstzrange
* daterange

=== 6.5 其他
* boolean
* cidr/inet/macaddr/macaddr8
* 数组
* json/jsonb

== 7. 高级特性
* with从句
* 批量插入: insert into select from / insert into values (),() / COPY
* upsert:
  insert into ... on conflict do {NOTHING | update set <colName> = EXCLUDED.colName}
* insert/update/delete .. returning *
* select from <table> TABLESAMPLE {SYSTEM | BERNOULLI}
* string_agg() / array_agg()
* 窗口函数
  ** row_number() : `select row_number() OVER partition by <colName>`,eg: 1,2,3, 1
  ** rank() : 分组重复则序号相同, 但下一个分组内不同行的序号保持增长,eg: 1,1,3
  ** dense_rank() : 分组重复则序号相同, 下一个分组内不同行的序号继续增长,eg: 1,1,2
  ** lag(field,offset,defaultValue): 获取行偏移offset那行某个字段的数据(offset为正向上偏移,为负则相反)
  ** first_value(field): 取分组第一行数据
  ** last_value(field): 取分组最后一行数据
  ** nth_value(field,line): 取分组指定行数据
  ** 别名: select ...[rank() over NAME] from <table> WINDOW <NAME> AS ()

== 8. 体系结构

=== 8.1 逻辑结构

 创建一个Database时会为这个Database创建一个名为public的默认schema.
 相同数据库不同schema可以拥有相同名称的table/index/view/sequence/function等

=== 8.2 物理结构
==== 8.2.1 OID
 OID,对象标识符,无符号4字节整数.所有的数据库对象由各自的OID管理

* 数据库对象OID保存在pg_database系统表里.
* 表/索引/序列等对象OID保存在pg_class系统表里.

==== 8.2.2 表空间
 初始化数据库目录时会自动创建两个表空间: pg_global和pg_default

* pg_global保存在global目录中, 用来保存系统表
* pg_default保存在base目录中, 默认数据库表空间

 每个数据库的oid都是base目录下的子目录, 表文件在所属数据库目录下以表OID命名.
 杜宇超过1GB大小的表文件则会自动切分为多个文件存储,以OID.<seq> 命名

=== 8.3 进程结构
* postmaster
* postgres
* syslogger
* checkpointer
* bgwriter
* walwriter

=== 8.4 内存结构

* 本地内存
** work_mem: ORDER BY/DISTINCT会用到
** maintenance_work_mem: VACUUM/REINDEX/CREATE INDEX会用到
** temp_buffers: 临时表操作会用到

* 共享内存
** shared buffer pool: 将表/索引文件载入内存
** WAL buffer: WAL文件持久化缓冲区
** CommitLog buffer: commit log中保存事务的状态,保存在缓冲区

== 9. 事务

|===
| 隔离级别 | 脏读 | 不可重复读 | 幻读 | 序列化异常

| Read Uncommitted
| x
|
|
|

| Read Committed
| x
|
|
|

| Repeatable Read
| x
| x
| x
|

| Serializable
| x
| x
| x
| x

|===

=== 9.1 查看全局事务默认隔离级别
 select name,setting from pg_settings where name='default_transaction_isolation';

=== 9.2 修改全局事务默认隔离级别
* 修改postgresql.conf的default_transaction_isolation参数
* `ALTER SYSTEM SET default_transaction_isolation TO 'REPEATABLE READ';`

=== 9.3 查看当前会话事务默认隔离级别
* `SHOW transaction_isolation;`
* `select current_setting('transaction_isolation');`

=== 9.4 设置当前会话事务默认隔离级别
* `set session characteristics as transaction isolation level REPEATABLE READ`
* `START|BEGIN TRANSACTION ISOLATION LEVEL READ UNCOMMITTED ... END`

== 10. 分区

> 将一个表根据不同的规则分成多个块的行为, 称为分区, 每一个分区称为分区表.

* 应用了分区规则的列会自动添加not null的约束.
* 如果插入的值根据规则找不到匹配的分区, 则会报错.
* PostgreSQL 10之后才内置分区功能, 支持Range和List分区, 11之后支持Hash分区.

=== 10.1 优势

* 每个分区表的索引相对于单表的索引大小会减小, 查询和更新的性能会提高
* 删除特定范围的数据可以通过直接删除某个分区表实现

TIP: 只有当表本身大小超过了物理内存的大小, 分区后才会受益.

=== 10.2 分区方式

* Range分区

 根据某一列值的范围插入相应的分区表, 比如根据日期范围分区, 仅支持单个列.

* List分区

 根据每个分区表的某一列值的集合分区. 支持多列/多表达式

* Hash分区

 根据某一列值的hash值分区


=== 10.3 SQL

[source,sql]
----
# 创建主表
CREATE TABLE [ IF NOT EXISTS ] parent_table ( [
  { column_name data_type [ COLLATE collation ] [ column_constraint [ ... ] ]
 ] ) PARTITION BY { RANGE | LIST | HASH } ( { column_name | ( expression ) }
# 创建range型分区表
CREATE TABLE partition_table_name PARTITION OF parent_table FOR VALUES FROM (start) TO (end);
# 创建list型分区表
CREATE TABLE partition_table_name PARTITION OF parent_table FOR VALUES IN (val1, val2) ;
# 创建hash型分区表
CREATE TABLE partition_table_name PARTITION OF parent_table FOR VALUES WITH (MODULUS 4, REMAINDER 3);

# 删除分区关系
ALTER TABLE parent_table ATTACH PARTITION partition_table_name
----

IMPORTANT: update语句违反了当前分区键的约束会报错

== 11. 清除WAL日志

文档: https://www.postgresql.org/docs/current/pgarchivecleanup.html
[source,bash]
----
pg_archivecleanup -d <archive_location> <oldest_kept_walfile>
----

如: `pg_archivecleanup -d /var/lib/postgresql/data/pg_wal 000000010000000000000036`
会将 000000010000000000000001~000000010000000000000035所有文件删除

TIP: `pg_archivecleanup -d . `ls -r | head -2 | tail -1``
