= Postgresql
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 3
:toc-title: 目录
:tabsize: 4
:docinfo: shared

== 安装

=== docker

[source,yaml]
.docker-compose.yml
----
version: '3'
services:
    postgresql:
        image: postgres:alpine
        container_name: postgresql
        volumes:
            - ~/volumes/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jy
            - POSTGRES_PASSWORD=123456
            - TZ=Asia/Shanghai
        network_mode: host

----

=== 安装包安装

[source,bash]
----
groupadd postgres
useradd postgres -g postgres
passwd postgres
mkdir -p /database/pg/pg_root
chown -R postgres:postgres /database/pg

sudo apt install postgresql-all
initdb -D /database/pg/pg_root -E UTF8 --locale=C -U postgres -W
----

== 基本命令

[source,bash]
----
# 创建db
createdb -U <username> <dbName>
# 删除b
dropdb -U <username> <dbName>
# 重建索引
reindexdb -d <dbName>
# 对数据库物理文件垃圾回收
vacuumdb <dbName>
# 清除数据库中未引用的大对象
vacuumlo <dbName>

pgdump
pgrestore
pgbench
# 登录数据库
psql [-h HOST] [-p PORT] DB [USERNAME]
# 获取pg配置
pg_config
# 获取数据库状态
pg_ctl -D <data-dir> status
# 启动数据库
postgres -D <data-dir> &
# 关闭数据库
pg_ctl -D <data-dir> -m [fast|smart|immediate]  -t <timeout> stop
----

== 配置

=== pg_hba.conf

[source,bash]
----
TYPE  DATABASE  USER  ADDRESS  METHOD
----

* TYPE: 允许连接的方式
** local: Unix domain socket
** host: TCP/IP, localhost default
** hostssl: OpenSSL restrict
** hostnossl: SSL not permitted
* METHOD: 认证方法
** trust
** password: 明文密码
** md5
** reject: 拒绝访问
** scram-sha-256

=== postgresql.conf

 postgresql 启动时postgresql.auto.conf会覆盖postgresql.conf内容
 更改配置生效: pg_ctl -D <data-dir> reload

== psql命令

* psql -c "SQL" [-d DB_NAME] [-U USERNAME] [-W PASSWORD] [-f SQL_FILE]
* \db: 查看表空间
* \l: 查看数据库
* \d <DB_NAME>: 查看表定义
* \dt+ <DB_NAME>: 查看表空间大小
* \di+ <IDX_NAME>: 查看索引空间大小
* \x: 切换查询显示模式
* COPY <DB> FROM|TO "FILE_PATH" : (大表)导入导出数据(必须有superuser权限)
* \copy <DB> FROM|TO "FILE_PATH" : (小表)导入导出数据
* \set VAR_NAME VALUE: 设置变量, :VAR_NAME 使用
* \timing: 开启sql计时

== Monitor

> https://www.postgresql.org/docs/current/monitoring-stats.html

[source,postgresql]
----
-- 查看活动会话
select pid, client_addr, query_start, state, query, wait_event, wait_event_type
from pg_stat_activity
where datid is not null
  and pid <> pg_backend_pid()
order by query_start desc;

-- 查看数据库连接数
select datname, client_addr, count(*)
from pg_stat_activity
where pid <> pg_backend_pid()
group by datname, client_addr
order by 1, 2, 3 desc;
----

.state字段含义
* active: 后台进程正在执行该SQL.
* idle: 后台进程处于空闲状态, 等待后续客户端发出命令.
* idle in transaction: 后台进程正在事务中.
* idle in transaction(aborted): 事务中的部分SQL异常.
* fastpath function call: 正在执行fast-path函数.

== 数据类型

=== 数字类型

* int2 int4 int8
* decimal/numeric[(precision,scale)]
* real 6位十进制精度浮点数
* double precision 15位十进制精度浮点数
* smallserial/serial/bigserial 2/4/8字节自增序列

=== 字符串类型

* varchar/character varying 变长
* character/char 定长
* text 变长, 长度小于1GB

=== 日期类型

* timestamp[without time zone] 不带时区的时间戳
* timestamp[with time zone] / timestamptz 带时区的时间戳
* date 日期
* time[with[out] time zone] 一天的时间
* interval 时间间隔

=== range类型

* int4range
* int8range
* numrange
* tsrange
* tstzrange
* daterange

=== 其他

* boolean
* cidr/inet/macaddr/macaddr8
* 数组
* json/jsonb

.json和jsonb的区别
* json以文本格式存储, jsonb以二进制存储.
* json输入和输出的键顺序保持一致, jsonb不保证.
* json会保留输入中的空格, jsonb不会.
* jsonb会删除重复的键, 只保留最后一个.

== 函数

[source,postgresql]
----
-- 计算字符串中的字符数
select char_length('abcd'); -- 4
-- 计算字符串占用的字节数
select octet_length('abcd'); -- 4
-- 获取字符在字符串中的位置, 位置从1开始
select position('bc' in 'abcd'); -- 2
-- 提取字符串中的子串
select substring('abcd' from 2 for 3); -- bcd
-- 分割字符串
select split_part('abc,def,ghi', ',', 2); -- def

-- 时间字段提取
select extract(year from '2019-07-15:12:34:56'::timestamp); -- 2019

-- 数组两种形式
select array[1,2,3];
select '{1,2,3}';
-- 获取数组指定下标元素, 位置从1开始
select arr[1] from (select array[1,2,3] arr) a; -- 1
-- 数组追加元素
select array_append(array[1,2,3],4); -- {1,2,3,4}
select array[1,2,3]||4;
select array[1,2,3] || array[1,2,3]; -- {1,2,3,1,2,3}
-- 数组删除元素
select array_remove(array[1,2,2,2,3],2); -- {1,3}
-- 判断数组是否相等
select array[1,2,3] = array [1,2,2,2,3]; -- false
-- 判断数组是否不相等
select array[1,2,3] <> array [1,2,2,2,3]; -- true
-- 比较数组
select array[1,2,3] <= array[2,1]; -- true
select array[1,2,3] >= array[2,1]; -- false
-- 判断数组包含关系
select array[1,2,3] @> array[1]; -- true
select array[1,2,3] <@ array[1,2,3,4,5]; -- true
-- 判断数组是否有公共元素
select array[1,2,3] && array[22]; -- false
-- 获取数组维度
select array_dims(array[[4],[3],[2],[1]]); -- [1:4] [1:1]
-- 获取数组指定维度的长度
select array_length(array[1,2,3,4],1); -- 3
select array_length(array[[4],[3],[2],[1]],2); -- 1
-- 获取数组某一个元素第一次出现的位置, 位置从1开始
select array_position(array[1,2,3],3); -- 3
-- 替换数组指定元素
select array_replace(array[1,2,3],2,11); -- {1,11,3}
-- 数组转为字符串
select array_to_string(array[1,2,3,null],',','99'); -- 1,2,3

-- 范围
select int4range(1,10,'[]'); -- [1,11)
select daterange('2019-06-01','2019-07-02'); -- [2019-06-01,2019-07-02)
-- 获取范围下界
select lower(int4range(1,10));
-- 获取范围上界
select upper(int4range(1,10));
-- 判断范围是否为空
select isempty(int4range(1,10));

-- json表示
select '{"a":1}'::json;
-- json字段值获取
select j -> 'a' from ( select '{"a":1}'::json j) sub; -- 1
-- 提取json中的键值对
select * from json_each('{"a":1,"b":2}'::json); -- a 1 b 2
select * from json_each_text('{"a":"aaa","b":2}'::json); -- a 1 b 2
-- 删除jsonb中的key
select '{"a":1,"b":2}'::jsonb - 'a'; -- {"b":2}
-- 判断key是否为顶层key
select '{"a":1,"b":2, "c":{"d":4}}'::jsonb ? 'd'; -- false
-- 获取json所有key
select json_object_keys('{"a":1,"b":2}'); -- a b
-- 删除json指定key
select '{"a":1,"b":2, "c":{"d":4}}'::jsonb - 'a'; -- {"b": 2, "c": {"d": 4}}
-- 删除json嵌套key
select '{"a":1,"b":2, "c":{"d":4}}'::jsonb #- '{c,d}'::text[];

----

== 高级特性

* with从句
* 批量插入: insert into select from / insert into values (),() / COPY
* upsert:
insert into ... on conflict do {NOTHING | update set <colName> = EXCLUDED.colName}
* insert/update/delete .. returning *
* select from <table> TABLESAMPLE {SYSTEM | BERNOULLI}
* string_agg() / array_agg()
* 窗口函数
** row_number() : `select row_number() OVER partition by <colName>`,eg: 1,2,3, 1
** rank() : 分组重复则序号相同, 但下一个分组内不同行的序号保持增长,eg: 1,1,3
** dense_rank() : 分组重复则序号相同, 下一个分组内不同行的序号继续增长,eg: 1,1,2
** lag(field,offset,defaultValue): 获取行偏移offset那行某个字段的数据(offset为正向上偏移,为负则相反)
** first_value(field): 取分组第一行数据
** last_value(field): 取分组最后一行数据
** nth_value(field,line): 取分组指定行数据
** 别名: select ...[rank() over NAME] from <table> WINDOW <NAME> AS ()

== 体系结构

=== 逻辑结构

 创建一个Database时会为这个Database创建一个名为public的默认schema.
 相同数据库不同schema可以拥有相同名称的table/index/view/sequence/function等

=== 物理结构

==== OID

 OID,对象标识符,无符号4字节整数.所有的数据库对象由各自的OID管理

* 数据库对象OID保存在pg_database系统表里.
* 表/索引/序列等对象OID保存在pg_class系统表里.

==== 表空间

 初始化数据库目录时会自动创建两个表空间: pg_global和pg_default

* pg_global保存在global目录中, 用来保存系统表
* pg_default保存在base目录中, 默认数据库表空间

 每个数据库的oid都是base目录下的子目录, 表文件在所属数据库目录下以表OID命名.
 杜宇超过1GB大小的表文件则会自动切分为多个文件存储,以OID.<seq> 命名

=== 进程结构

* postmaster
* postgres
* syslogger
* checkpointer
* bgwriter
* walwriter

=== 内存结构

* 本地内存
** work_mem: ORDER BY/DISTINCT会用到
** maintenance_work_mem: VACUUM/REINDEX/CREATE INDEX会用到
** temp_buffers: 临时表操作会用到

* 共享内存
** shared buffer pool: 将表/索引文件载入内存
** WAL buffer: WAL文件持久化缓冲区
** CommitLog buffer: commit log中保存事务的状态,保存在缓冲区

== 事务

[source,sql]
----
create table tbl_mvcc
(
    id   bigserial primary key,
    ival integer
);
insert into tbl_mvcc(ival) values (1);
----

=== 脏读

> 一个事务看到了另外一个事务未提交的数据.
(PostgreSQL下不可复现)

.Dirty Read
|===
| console1 | console2

a|

```sql
-- MySQL
set session transaction isolation level read uncommitted;
start transaction;
select * from tbl_mvcc where id = 1; -- 1
```

|

|
a|
```sql
start transaction;
update tbl_mvcc set ival = 10 where id = 1;
```

a|
```sql
select * from tbl_mvcc where id = 1; -- 10
```
|

|===

=== 不可重复读

> 一个事务查询结果与第一次的结果不同.(受到其他已提交事务 *UPDATE* 的影响)

.Non-repeatable Read
|===
| console1 | console2

a|

```sql
begin transaction isolation level read committed;
select * from tbl_mvcc where id = 1; -- 1
```

|

|
a|
```sql
begin;
update tbl_mvcc set ival = 10 where id = 1;
end;
```

a|
```sql
select * from tbl_mvcc where id = 1; -- 10
```
|

|===

=== 幻读

> 一个事务两次查询的结果集数量不一致.(受到其他已提交事务 *INSERT/DELETE* 的影响)

.Phantom Read
|===
| console1 | console2

a|

```sql
begin transaction isolation level read committed;
select * from tbl_mvcc where id between 1 and 10;
```
|

|
a|
```sql
begin;
delete from tbl_mvcc where id > 5 ;
end;
```

a|
```sql
-- 与之前结果相比少了一些数据
select * from tbl_mvcc where id between 1 and 10;
```
|

|===

.Serialization Anomaly
|===
| console1 | console2

a|
```sql
begin transaction isolation level repeatable read;
select ival from tbl_mvcc where id =1;
```
|

|
a|
```sql
update tbl_mvcc set ival = 10 where id = 1;
```

a|
```sql
update tbl_mvcc set ival = 100 where id = 1;
-- [40001] ERROR: could not serialize access due to concurrent update
```
|

|===

.PostgreSQL事务隔离级别
|===
| 隔离级别 | 脏读 | 不可重复读 | 幻读 | 序列化异常

| Read Uncommitted
| x
|
|
|

| Read Committed
| x
|
|
|

| Repeatable Read
| x
| x
| x
|

| Serializable
| x
| x
| x
| x

|===

=== 查看全局事务默认隔离级别

 select name,setting from pg_settings where name='default_transaction_isolation';

=== 修改全局事务默认隔离级别

* 修改postgresql.conf的default_transaction_isolation参数
* `ALTER SYSTEM SET default_transaction_isolation TO 'REPEATABLE READ';`

=== 查看当前会话事务默认隔离级别

* `SHOW transaction_isolation;`
* `select current_setting('transaction_isolation');`

=== 设置当前会话事务默认隔离级别

* `set session characteristics as transaction isolation level REPEATABLE READ`
* `START|BEGIN TRANSACTION ISOLATION LEVEL READ UNCOMMITTED ... END`

== 分区

> 将一个表根据不同的规则分成多个块的行为, 称为分区, 每一个分区称为分区表.

* 应用了分区规则的列会自动添加not null的约束.
* 如果插入的值根据规则找不到匹配的分区, 则会报错.
* PostgreSQL 10之后才内置分区功能, 支持Range和List分区, 11之后支持Hash分区.

=== 优势

* 每个分区表的索引相对于单表的索引大小会减小, 查询和更新的性能会提高
* 删除特定范围的数据可以通过直接删除某个分区表实现

TIP: 只有当表本身大小超过了物理内存的大小, 分区后才会受益.

=== 分区方式

* Range分区

 根据某一列值的范围插入相应的分区表, 比如根据日期范围分区, 仅支持单个列.

* List分区

 根据每个分区表的某一列值的集合分区. 支持多列/多表达式

* Hash分区

 根据某一列值的hash值分区

=== SQL

[source,postgresql]
----
-- 创建主表
CREATE TABLE [ IF NOT EXISTS ] parent_table ( [
  { column_name data_type [ COLLATE collation ] [ column_constraint [ ... ] ]
 ] ) PARTITION BY { RANGE | LIST | HASH } ( { column_name | ( expression ) }
-- 创建range型分区表
CREATE TABLE partition_table_name PARTITION OF parent_table FOR VALUES FROM (start) TO (end);
-- 创建list型分区表
CREATE TABLE partition_table_name PARTITION OF parent_table FOR VALUES IN (val1, val2) ;
-- 创建hash型分区表
CREATE TABLE partition_table_name PARTITION OF parent_table FOR VALUES WITH (MODULUS 4, REMAINDER 3);

-- 删除分区关系
ALTER TABLE parent_table ATTACH PARTITION partition_table_name
----

IMPORTANT: update语句违反了当前分区键的约束会报错

== 清除WAL日志

文档: https://www.postgresql.org/docs/current/pgarchivecleanup.html

[source,bash]
----
pg_archivecleanup -d <archive_location> <oldest_kept_walfile>
----

如: `pg_archivecleanup -d /var/lib/postgresql/data/pg_wal 000000010000000000000036`
会将 000000010000000000000001~000000010000000000000035所有文件删除

TIP: `pg_archivecleanup -d . `ls -r | head -2 | tail -1``

== 查询优化

=== 逻辑优化

根据关系代数等价式优化查询

* 尽量将选择操作下推到叶子节点来做
* 尽量在叶子节点上使用投影缩小中间结果

=== 物理优化

通过代价估算的方式挑选代价比较低的物理路径


