= Spring
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: idea
:hardbreaks:
:sectlinks:
:sectnums:
:stem:
:toc: left
:toclevels: 3
:toc-title: 目录
:tabsize: 4

== IoC Demo

=== Bean

[source,java]
.CallbackBean.java
----
public class CallbackBean implements InitializingBean, DisposableBean, Lifecycle, BeanPostProcessor {

    private boolean running = false;

    public CallbackBean() {
        System.out.println("CallbackBean constructor");
    }

    @Override
    public void afterPropertiesSet() {
        System.out.println("DisposableBean.afterPropertiesSet");
    }

    @Override
    public void destroy() {
        System.out.println("DisposableBean.destroy");
    }

    @PostConstruct
    public void PostConstruct() {
        System.out.println("PostConstruct");
    }

    @PreDestroy
    public void preDestroy() {
        System.out.println("PreDestroy");
    }

    public void init() {
        System.out.println("init...");
    }

    public void close() {
        System.out.println("close...");
    }

    @Override
    public void start() {
        System.out.println("Lifecycle start...");
        running = true;
    }

    @Override
    public void stop() {
        System.out.println("Lifecycle stop...");
    }

    @Override
    public boolean isRunning() {
        return running;
    }

    @Override
    public Object postProcessBeforeInitialization(Object bean, String beanName) {
        System.out.println("postProcessBeforeInitialization");
        return bean;
    }

    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) {
        System.out.println("postProcessAfterInitialization");
        return bean;
    }
}
----

=== Configuration

[source,java]
.BeanConfiguration.java
----
@Configuration
@ComponentScan("me.jy.bean")
public class BeanConfiguration {
}
----

=== Main方法

[source,java]
.Bootstrap.java
----
public class Bootstrap {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext(BeanConfiguration.class); // <1>
        applicationContext.start();
        applicationContext.close();
    }
}
----
<1> 初始化 `ApplicationContext` , 注册 `BeanConfiguration` 配置类.

== IoC启动过程

=== ApplicationContext初始化

[source,java]
.AnnotationConfigApplicationContext.java
----
    public AnnotationConfigApplicationContext() {
		this.reader = new AnnotatedBeanDefinitionReader(this); // <1>
		this.scanner = new ClassPathBeanDefinitionScanner(this); // <2>
	}

    public AnnotationConfigApplicationContext(Class<?>... annotatedClasses) {
		this();
		register(annotatedClasses); // <3>
		refresh();
	}
----

<1> 初始化 `AnnotatedBeanDefinitionReader`, 创建一个 `Environment` 对象.
注册一些 `BeanDefinitionRegistryPostProcessor`/`BeanPostProcessor`/`BeanFactoryPostProcessor`.
<2> 初始化 `ClassPathBeanDefinitionScanner`.
<3> 使用 `AnnotatedBeanDefinitionReader` 注册配置类.

=== 注册BeanDefinition

[source,java]
.AnnotatedBeanDefinitionReader.java
----
    <T> void doRegisterBean(Class<T> annotatedClass, @Nullable Supplier<T> instanceSupplier, @Nullable String name,
			@Nullable Class<? extends Annotation>[] qualifiers, BeanDefinitionCustomizer... definitionCustomizers) {

		AnnotatedGenericBeanDefinition abd = new AnnotatedGenericBeanDefinition(annotatedClass); // <1>
		if (this.conditionEvaluator.shouldSkip(abd.getMetadata())) { // <2>
			return;
		}

		abd.setInstanceSupplier(instanceSupplier);
		ScopeMetadata scopeMetadata = this.scopeMetadataResolver.resolveScopeMetadata(abd); // <3>
		abd.setScope(scopeMetadata.getScopeName());
		String beanName = (name != null ? name : this.beanNameGenerator.generateBeanName(abd, this.registry));

		AnnotationConfigUtils.processCommonDefinitionAnnotations(abd); // <4>
		if (qualifiers != null) {
			for (Class<? extends Annotation> qualifier : qualifiers) {
				if (Primary.class == qualifier) {
					abd.setPrimary(true);
				}
				else if (Lazy.class == qualifier) {
					abd.setLazyInit(true);
				}
				else {
					abd.addQualifier(new AutowireCandidateQualifier(qualifier));
				}
			}
		}
		for (BeanDefinitionCustomizer customizer : definitionCustomizers) {
			customizer.customize(abd);
		}

		BeanDefinitionHolder definitionHolder = new BeanDefinitionHolder(abd, beanName);
		definitionHolder = AnnotationConfigUtils.applyScopedProxyMode(scopeMetadata, definitionHolder, this.registry); // <5>
		BeanDefinitionReaderUtils.registerBeanDefinition(definitionHolder, this.registry); // <6>
	}
----

<1> 配置类包装成 `AnnotatedGenericBeanDefinition` 对象.
<2> 判断是否满足注册bean的条件.
<3> 解析scope.
<4> 解析bean类上的 `@Lazy/@Primary/@DependsOn/@Role/@Description` 注解.
<5> 根据 `scopeMode` 判断生成对应的代理类.
<6> 注册beanDefinition(将 `definitionHolder` 放到 `BeanFactory` 的 `beanDefinitionMap` 中).

=== refresh

[source,java]
.AbstractApplicationContext.java
----
    @Override
	public void refresh() throws BeansException, IllegalStateException {
		synchronized (this.startupShutdownMonitor) {
			// Prepare this context for refreshing.
			prepareRefresh(); // <1>
			// Tell the subclass to refresh the internal bean factory.
			ConfigurableListableBeanFactory beanFactory = obtainFreshBeanFactory();
			// Prepare the bean factory for use in this context.
			prepareBeanFactory(beanFactory); // <2>
			try {
				// Allows post-processing of the bean factory in context subclasses.
				postProcessBeanFactory(beanFactory);
				// Invoke factory processors registered as beans in the context.
				invokeBeanFactoryPostProcessors(beanFactory); // <3>
				// Register bean processors that intercept bean creation.
				registerBeanPostProcessors(beanFactory); // <4>
				// Initialize message source for this context.
				initMessageSource(); // <5>
				// Initialize event multicaster for this context.
				initApplicationEventMulticaster(); // <6>
				// Initialize other special beans in specific context subclasses.
				onRefresh();
				// Check for listener beans and register them.
				registerListeners();
				// Instantiate all remaining (non-lazy-init) singletons.
				finishBeanFactoryInitialization(beanFactory); // <7>
				// Last step: publish corresponding event.
				finishRefresh(); // <8>
			}
			catch (BeansException ex) {
				if (logger.isWarnEnabled()) {
					logger.warn("Exception encountered during context initialization - " + "cancelling refresh attempt: " + ex);
				}
				// Destroy already created singletons to avoid dangling resources.
				destroyBeans();
				// Reset 'active' flag.
				cancelRefresh(ex);
				// Propagate exception to caller.
				throw ex;
			}
			finally {
				// Reset common introspection caches in Spring's core, since we
				// might not ever need metadata for singleton beans anymore...
				resetCommonCaches();
			}
		}
	}
----
<1> 子类自定义初始化一些 `properties` , 校验必填属性.
<2> 设置 `BeanFactory` 的一些属性, 注册 `environment/systemProperties/systemEnvironment` .
<3> 调用 `ConfigurationClassPostProcessor.processConfigBeanDefinitions` 解析 `Configuration` 类并生成CGLIB代理, 根据 `@ComponentScan` 扫描包下面的bean注册到 `BeanFactory` 中.
<4> 注册 `beanPostProcessor` 到 `BeanFactory` 中.
<5> 注册 `DelegatingMessageSource` .
<6> 注册 `ApplicationEventMulticaster` .
<7> 调用 `BeanFactory.getBean()` 初始化所有非懒加载的bean.
<8> 注册 `LifecycleProcessor` , 执行 `onRefresh` 方法, 发布 `ContextRefreshedEvent` .

== Spring AOP

=== 术语

* Aspect:
声明需要关注的类/方法的一个地方.
* JoinPoint:
代表正在执行的方法.
* Advice:
表示JoinPoint何时被执行, 如 `Before`, `AfterReturning`, `AfterThrowing`, `After`, `Around`.
* Pointcut:
连接点匹配判断.
* Introduction:
为特定类型声明额外的方法/属性.
* Target object:
被AOP的原始对象.
* AOP proxy:
被AOP框架生成代理的对象.
* Weaving:
基于普通对象和切面生成代理对象的过程, 可以在编译时/加载时/运行时进行.

=== Pointcut

* 匹配方法
* execution: `execution(modifiers-pattern? ret-type-pattern declaring-type-pattern?name-pattern(param-pattern) throws-pattern?)`
* 匹配包/类型
** within
* 匹配对象
** this
** bean
** target
* 匹配注解
** @target:
RetentionPolicy为class
** @args
** @within:
RetentionPolicy为runtime
** @annotation
* 匹配参数
** args

.示例:
[source,java]
----
execution(public * *(..)) // 匹配所有公共方法
execution(* set*(..)) // 匹配所有以set开头的方法
execution(* com.xyz.service.AccountService.*(..)) // 匹配AccountService里所有的方法
execution(* com.xyz.service.*.*(..)) // 匹配com.xyz.service包下所有的方法
execution(* com.xyz.service..*.*(..)) // 匹配com.xyz.service包及其子包下所有的方法

within(com.xyz.service.*) // 匹配com.xyz.service包下所有的方法
within(com.xyz.service..*) // 匹配com.xyz.service包及其子包下所有的方法

this(com.xyz.service.AccountService) // 匹配AccountService所有子类里的方法
target(com.xyz.service.AccountService)

bean(tradeService) // 匹配beanName为"tradeService"的类下的方法.
bean(*Service) // 匹配beanName以"Service"结尾的类下的方法.

args(java.io.Serializable) // 匹配参数只有一个并且类型为Serializable的方法

@target(org.springframework.transaction.annotation.Transactional) // 匹配有@Transactional注解的类下的方法
@within(org.springframework.transaction.annotation.Transactional)
@annotation(org.springframework.transaction.annotation.Transactional) // 匹配有@Transactional注解的方法
@args(com.xyz.security.Classified) // 匹配参数只有一个并且参数上有@Classified的方法

----

== QA

[qanda]
IoC?::
对象自身生命周期的控制以及与其他对象的依赖关系交由Spring容器管理.

依赖注入的方式?::
* 构造函数注入
* setter方法注入
* 接口注入

ApplicationContext与BeanFactory的区别?::
* BeanFactory在spring-beans包中, ApplicationContext在spring-context包中.
* ApplicationContext扩展了BeanFactory的功能:
** MessageSource:
实现国际化功能.
** EventPublisher:
实现事件订阅发布功能.
** LifeCycle:
管理生命周期.
** 集成AOP.
** 新增一些应用层context, 如 `WebApplicationContext` .
** ...

如何手动注册bean?::
* BeanFactory.registerBeanDefinition:
通过BeanFactory注册
* ApplicationContext.register:
通过ApplicationContext注册
* ApplicationContext.scan: 扫描包下所有的bean

如何实例化bean?::
* 构造函数
* static factory method
* instance factory method

单例bean中如何注入prototype型bean?::
* `@Lookup` 一个抽象方法
* `ObjectFactory/Provider`

bean的生命周期?::
. @PostConstruct
. DisposableBean.afterPropertiesSet
. initMethod
. BeanPostProcessor.postProcessBeforeInitialization
. BeanPostProcessor.postProcessAfterInitialization
. LifeCycle.start
. LifeCycle.stop
. @PreDestroy
. DisposableBean.destroy
. destroyMethod

Configuration类实例方法中直接调用beanMethod为什么可以直接得到bean?::
Spring会为每个Configuration类生成CGLIB代理类, 代理类会拦截所有的beanMethod, 返回值为从BeanFactory中get到的bean.

什么情况下会发生Bean循环引用?::
* 两个bean互相在构造函数中注入
* 两个prototype类型的bean互相注入

Spring如何检测Bean循环引用?::
参见 `DefaultSingletonBeanRegistry.beforeSingletonCreation` 方法. 每个bean在创建前 `beanName` 会放到 `singletonsCurrentlyInCreation` 这个set中, bean创建完会从这个set中移出.
解析构造函数上 `@Autowired` 注解时会看需要注入的bean在不在这个set中, 如果在, 则抛出循环引用异常.

Bean循环引用如何解决?::
`@Autowired` 时添加 `@Lazy` 注解, 并且构造函数中不要去获取注入对象的属性/调用方法.
*原理* :
如果注入时有 `@Lazy` 注解, 则会注入一个代理, 只有当使用这个字段时才会从 `BeanFactory` 中获取真正的bean.

为什么JDK动态代理调用同类中方法时不走切面?::
JDK动态代理会生成一个子类, 调用这个子类的方法时会直接调用 `InvocationHandler` 中的invoke方法, 并且传递对象的是原被代理的对象.
所以在被代理的对象中直接调用同类的方法不会调用切面的代码.

使用CGLIB代理有什么要求?::
* 被代理的类不能是 `final` 类.
* 被代理的方法不能是私有方法.

Spring配置的placeholder占位符是如何替换的, 有什么办法可以自定义替换方式?::
依靠 `Environment` 对象的 `propertyResolver` 解析:
替换掉 `${}` 占位符, 再从 `Environment` 的 `propertySources` 中获取该属性名对应的值.
